import * as fs from 'fs';
import * as path from 'path';
import { OpenAPISpec, OpenAPIParser } from '@steel-core/core';

export default class PythonGenerator {
  async generate(spec: OpenAPISpec, outputDir: string): Promise<void> {
    fs.mkdirSync(outputDir, { recursive: true });

    const parser = new OpenAPIParser();
    const operations = parser.getOperations(spec);
    const className = this.toClassName(spec.info.title);

    const clientCode = this.renderClient(className, spec, operations);
    fs.writeFileSync(path.join(outputDir, 'client.py'), clientCode);
    fs.writeFileSync(path.join(outputDir, '__init__.py'), `from .client import ${className}\n\n__all__ = ["${className}"]\n`);
    fs.writeFileSync(path.join(outputDir, 'requirements.txt'), 'httpx>=0.27.0\n');

    console.log(`  Created: client.py, __init__.py, requirements.txt`);
  }

  private renderClient(
    className: string,
    spec: OpenAPISpec,
    operations: ReturnType<OpenAPIParser['getOperations']>
  ): string {
    const methods = operations.map((op) => this.renderMethod(op)).join('\n\n');

    return `"""
${spec.info.title} v${spec.info.version} — auto-generated by Steel Core
${spec.info.description ? `\n${spec.info.description}\n` : ''}"""
from __future__ import annotations
from typing import Any, Optional
import httpx


class ${className}:
    def __init__(self, base_url: str, api_key: Optional[str] = None, timeout: float = 30.0) -> None:
        headers: dict[str, str] = {"Content-Type": "application/json"}
        if api_key:
            headers["Authorization"] = f"Bearer {api_key}"
        self._client = httpx.Client(base_url=base_url, headers=headers, timeout=timeout)

    def __enter__(self) -> "${className}":
        return self

    def __exit__(self, *_: Any) -> None:
        self._client.close()

${methods}
`;
  }

  private renderMethod(op: { path: string; method: string; operation: import('@steel-core/core').Operation }): string {
    const name = op.operation.operationId
      ? this.toSnakeCase(op.operation.operationId)
      : `${op.method}_${this.toSnakeCase(op.path.replace(/[{}]/g, '').replace(/\//g, '_'))}`;

    const pathParams = (op.operation.parameters ?? [])
      .filter((p) => p.in === 'path')
      .map((p) => `${this.toSnakeCase(p.name)}: str`);

    const queryParams = (op.operation.parameters ?? [])
      .filter((p) => p.in === 'query')
      .map((p) => `${this.toSnakeCase(p.name)}: Optional[str] = None`);

    const hasBody = !!op.operation.requestBody;
    const bodyParam = hasBody ? ['body: Optional[dict[str, Any]] = None'] : [];

    const allParams = ['self', ...pathParams, ...queryParams, ...bodyParam].join(', ');
    const urlPath = op.path.replace(/{(\w+)}/g, '{$1}');
    const docstring = op.operation.summary ?? op.operation.description ?? '';

    return `    def ${name}(${allParams}) -> Any:
        """${docstring}"""
        resp = self._client.${op.method}(f"${urlPath}"${hasBody ? ', json=body' : ''})
        resp.raise_for_status()
        return resp.json()`;
  }

  private toClassName(title: string): string {
    return title.replace(/[^a-zA-Z0-9]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()).replace(/\s/g, '') + 'Client';
  }

  private toSnakeCase(str: string): string {
    return str.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '').replace(/[^a-z0-9_]/g, '_');
  }
}
