import * as fs from 'fs';
import * as path from 'path';
import { OpenAPISpec, OpenAPIParser, SchemaObject, ResolvedModel, Operation } from '@steel-core/core';

export default class CSharpGenerator {
  private parser!: OpenAPIParser;
  private ns!: string;       // C# namespace, e.g. WidgetApi
  private className!: string; // e.g. WidgetApiClient

  async generate(spec: OpenAPISpec, outputDir: string): Promise<void> {
    fs.mkdirSync(outputDir, { recursive: true });
    this.parser = new OpenAPIParser();
    this.parser.parse(spec);
    this.ns        = this.toPascalCase(spec.info.title);
    this.className = `${this.ns}Client`;

    const models     = this.parser.getModels();
    const operations = this.parser.getOperations(spec);

    fs.writeFileSync(path.join(outputDir, 'Models.cs'),        this.renderModels(models));
    fs.writeFileSync(path.join(outputDir, 'ApiException.cs'),  this.renderApiException());
    fs.writeFileSync(path.join(outputDir, 'RetryConfig.cs'),   this.renderRetryConfig());
    fs.writeFileSync(path.join(outputDir, 'HttpTransport.cs'), this.renderHttpTransport());
    fs.writeFileSync(path.join(outputDir, 'Pagination.cs'),    this.renderPagination());
    fs.writeFileSync(path.join(outputDir, `${this.className}.cs`), this.renderClient(spec, operations));
    fs.writeFileSync(path.join(outputDir, `${this.ns}.csproj`),    this.renderCsproj(spec));

    console.log(`  Created: Models.cs, ApiException.cs, RetryConfig.cs, HttpTransport.cs, Pagination.cs, ${this.className}.cs, ${this.ns}.csproj`);
  }

  // ── Models.cs ─────────────────────────────────────────────────────────────

  private renderModels(models: ResolvedModel[]): string {
    const body = models.map((m) => this.renderModel(m)).join('\n\n');
    return `// <auto-generated> Code generated by Steel Core — do not edit manually. </auto-generated>
using System.Text.Json.Serialization;

namespace ${this.ns};

${body}
`;
  }

  private renderModel(model: ResolvedModel): string {
    const name   = this.toPascalCase(model.name);
    const schema = model.schema;

    // Enum
    if (schema.enum) {
      const members = schema.enum
        .map((v) => `    [JsonStringEnumMemberName("${v}")]\n    ${this.toPascalCase(String(v))}`)
        .join(',\n\n');
      return `[JsonConverter(typeof(JsonStringEnumConverter))]\npublic enum ${name}\n{\n${members}\n}`;
    }

    // oneOf/anyOf → object alias
    if (schema.oneOf ?? schema.anyOf) {
      const variants = (schema.oneOf ?? schema.anyOf)!.map((s) => this.schemaToCsType(s)).join(', ');
      return `// ${name} is one of: ${variants}\npublic class ${name} { }`;
    }

    // Object → record with init-only properties
    const props    = schema.properties ?? {};
    const required = new Set(schema.required ?? []);
    const doc      = schema.description ? `/// <summary>${schema.description}</summary>\n` : '';

    const members = Object.entries(props).map(([propName, propSchema]) => {
      const csType   = this.schemaToCsType(propSchema, !required.has(propName));
      const propId   = this.toPascalCase(propName);
      const jsonAttr = `[JsonPropertyName("${propName}")]`;
      const fieldDoc = propSchema.description ? `    /// <summary>${propSchema.description}</summary>\n` : '';
      // Append ? only if the type isn't already nullable
      const nullableSuffix = (!required.has(propName) && !csType.endsWith('?')) ? '?' : '';
      if (required.has(propName)) {
        return `${fieldDoc}    ${jsonAttr}\n    public required ${csType} ${propId} { get; init; }`;
      }
      return `${fieldDoc}    ${jsonAttr}\n    public ${csType}${nullableSuffix} ${propId} { get; init; }`;
    });

    const body = members.length ? members.join('\n\n') : '    // no properties';
    return `${doc}public record ${name}\n{\n${body}\n}`;
  }

  // ── ApiException.cs ───────────────────────────────────────────────────────

  private renderApiException(): string {
    return `// <auto-generated> Code generated by Steel Core — do not edit manually. </auto-generated>
namespace ${this.ns};

/// <summary>Thrown when the API returns a non-2xx HTTP response.</summary>
public class ApiException : Exception
{
    public int    StatusCode { get; }
    public string Body       { get; }
    public string Url        { get; }

    public ApiException(int statusCode, string body, string url)
        : base($"HTTP {statusCode} {url}: {body[..Math.Min(body.Length, 200)]}")
    {
        StatusCode = statusCode;
        Body       = body;
        Url        = url;
    }

    public bool IsRetryable =>
        StatusCode == 429 || (StatusCode >= 500 && StatusCode < 600);
}

/// <summary>Thrown when the server returns 429 Too Many Requests.</summary>
public class RateLimitException : ApiException
{
    public RateLimitException(string body, string url) : base(429, body, url) { }
}

/// <summary>Thrown when the server returns 401 or 403.</summary>
public class AuthException : ApiException
{
    public AuthException(int statusCode, string body, string url) : base(statusCode, body, url) { }
}
`;
  }

  // ── RetryConfig.cs ────────────────────────────────────────────────────────

  private renderRetryConfig(): string {
    return `// <auto-generated> Code generated by Steel Core — do not edit manually. </auto-generated>
namespace ${this.ns};

/// <summary>Configuration for automatic retry with exponential backoff.</summary>
/// <param name="MaxRetries">Number of retries after the first attempt. Default: 3.</param>
/// <param name="BaseDelay">Initial backoff delay. Default: 1 second.</param>
/// <param name="MaxDelay">Maximum backoff delay. Default: 60 seconds.</param>
/// <param name="Jitter">Add ±25% randomness to delay. Default: true.</param>
public record RetryConfig(
    int      MaxRetries = 3,
    TimeSpan BaseDelay  = default,
    TimeSpan MaxDelay   = default,
    bool     Jitter     = true)
{
    /// <summary>Default retry configuration.</summary>
    public static readonly RetryConfig Default = new(
        MaxRetries: 3,
        BaseDelay:  TimeSpan.FromSeconds(1),
        MaxDelay:   TimeSpan.FromSeconds(60),
        Jitter:     true);

    /// <summary>No retries.</summary>
    public static readonly RetryConfig None = new(MaxRetries: 0);

    // Ensure non-default TimeSpan values are sensible
    internal TimeSpan EffectiveBaseDelay => BaseDelay == default ? TimeSpan.FromSeconds(1)  : BaseDelay;
    internal TimeSpan EffectiveMaxDelay  => MaxDelay  == default ? TimeSpan.FromSeconds(60) : MaxDelay;
}
`;
  }

  // ── HttpTransport.cs ──────────────────────────────────────────────────────

  private renderHttpTransport(): string {
    return `// <auto-generated> Code generated by Steel Core — do not edit manually. </auto-generated>
using System.Net;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;

namespace ${this.ns};

/// <summary>Internal HTTP transport with retry, backoff, and Retry-After support.</summary>
internal sealed class HttpTransport : IDisposable
{
    private static readonly int[]    RetryableStatus = [429, 500, 502, 503, 504];
    private static readonly Random   Rng             = new();
    private static readonly JsonSerializerOptions JsonOpts = new()
    {
        PropertyNameCaseInsensitive = true,
        DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull,
    };

    private readonly HttpClient    _client;
    private readonly RetryConfig   _retry;
    private readonly string        _baseUrl;

    internal HttpTransport(string baseUrl, IDictionary<string, string> headers, RetryConfig retry)
    {
        _baseUrl = baseUrl.TrimEnd('/');
        _retry   = retry;
        _client  = new HttpClient { Timeout = TimeSpan.FromSeconds(30) };
        foreach (var (k, v) in headers) _client.DefaultRequestHeaders.Add(k, v);
    }

    internal async Task<T?> RequestAsync<T>(
        string method, string path,
        IDictionary<string, object?>? queryParams = null,
        object? body = null,
        CancellationToken ct = default)
    {
        var url = BuildUrl(path, queryParams);
        Exception? last = null;

        for (int attempt = 0; attempt <= _retry.MaxRetries; attempt++)
        {
            if (attempt > 0)
                await Task.Delay(Backoff(attempt - 1), ct).ConfigureAwait(false);

            using var req = new HttpRequestMessage(new HttpMethod(method), url);
            if (body is not null)
            {
                req.Content = new StringContent(
                    JsonSerializer.Serialize(body, JsonOpts),
                    Encoding.UTF8, "application/json");
            }

            HttpResponseMessage? resp = null;
            try
            {
                resp = await _client.SendAsync(req, ct).ConfigureAwait(false);
            }
            catch (Exception ex) when (ex is HttpRequestException or TaskCanceledException)
            {
                last = ex;
                continue;
            }

            using (resp)
            {
                if (Array.IndexOf(RetryableStatus, (int)resp.StatusCode) >= 0
                    && attempt < _retry.MaxRetries)
                {
                    if (resp.Headers.TryGetValues("Retry-After", out var ra)
                        && double.TryParse(ra.First(), out var secs))
                    {
                        await Task.Delay(TimeSpan.FromSeconds(secs), ct).ConfigureAwait(false);
                    }
                    last = new ApiException((int)resp.StatusCode, "", url);
                    continue;
                }

                if (!resp.IsSuccessStatusCode)
                {
                    var errBody = await resp.Content.ReadAsStringAsync(ct).ConfigureAwait(false);
                    throw resp.StatusCode switch
                    {
                        HttpStatusCode.TooManyRequests => new RateLimitException(errBody, url),
                        HttpStatusCode.Unauthorized or
                        HttpStatusCode.Forbidden      => new AuthException((int)resp.StatusCode, errBody, url),
                        _                             => new ApiException((int)resp.StatusCode, errBody, url),
                    };
                }

                if (resp.StatusCode == HttpStatusCode.NoContent) return default;
                var json = await resp.Content.ReadAsStringAsync(ct).ConfigureAwait(false);
                return JsonSerializer.Deserialize<T>(json, JsonOpts);
            }
        }

        throw last ?? new ApiException(0, "Request failed after retries", url);
    }

    private TimeSpan Backoff(int attempt)
    {
        var ms = Math.Min(
            _retry.EffectiveBaseDelay.TotalMilliseconds * Math.Pow(2, attempt),
            _retry.EffectiveMaxDelay.TotalMilliseconds);
        if (_retry.Jitter) ms *= 0.75 + Rng.NextDouble() * 0.5;
        return TimeSpan.FromMilliseconds(ms);
    }

    private static string BuildUrl(string path, IDictionary<string, object?>? queryParams)
    {
        if (queryParams is null || queryParams.Count == 0) return path;
        var qs = string.Join("&", queryParams
            .Where(kv => kv.Value is not null)
            .Select(kv => $"{Uri.EscapeDataString(kv.Key)}={Uri.EscapeDataString(kv.Value!.ToString()!)}"));
        return qs.Length == 0 ? path : $"{path}?{qs}";
    }

    public void Dispose() => _client.Dispose();
}
`;
  }

  // ── Pagination.cs ─────────────────────────────────────────────────────────

  private renderPagination(): string {
    return `// <auto-generated> Code generated by Steel Core — do not edit manually. </auto-generated>
namespace ${this.ns};

/// <summary>
/// A cursor-paginated result. Implements <see cref="IAsyncEnumerable{T}"/> for
/// transparent auto-pagination with <c>await foreach</c>.
/// </summary>
/// <example>
/// <code>
/// await foreach (var widget in client.ListWidgetsAsync())
///     Console.WriteLine(widget.Name);
/// </code>
/// </example>
public sealed class CursorPage<T> : IAsyncEnumerable<T>
{
    public IReadOnlyList<T> Items      { get; }
    public string?          NextCursor { get; }
    public bool             HasNext    => NextCursor is not null;

    private readonly Func<string, Task<CursorPage<T>>> _fetch;

    public CursorPage(IReadOnlyList<T> items, string? nextCursor,
                      Func<string, Task<CursorPage<T>>> fetch)
    {
        Items      = items;
        NextCursor = nextCursor;
        _fetch     = fetch;
    }

    /// <summary>Collect all items across all pages into a list.</summary>
    public async Task<IReadOnlyList<T>> ToListAsync(CancellationToken ct = default)
    {
        var all = new List<T>(Items);
        var page = this;
        while (page.HasNext)
        {
            page = await page._fetch(page.NextCursor!).ConfigureAwait(false);
            all.AddRange(page.Items);
        }
        return all;
    }

    public async IAsyncEnumerator<T> GetAsyncEnumerator(CancellationToken ct = default)
    {
        var page = this;
        while (true)
        {
            foreach (var item in page.Items)
            {
                ct.ThrowIfCancellationRequested();
                yield return item;
            }
            if (!page.HasNext) break;
            page = await page._fetch(page.NextCursor!).ConfigureAwait(false);
        }
    }
}

/// <summary>
/// An offset/limit-paginated result. Implements <see cref="IAsyncEnumerable{T}"/>.
/// </summary>
public sealed class OffsetPage<T> : IAsyncEnumerable<T>
{
    public IReadOnlyList<T> Items   { get; }
    public long?            Total   { get; }
    public long             Offset  { get; }
    public long             Limit   { get; }
    public bool             HasNext { get; }

    private readonly Func<long, long, Task<OffsetPage<T>>> _fetch;

    public OffsetPage(IReadOnlyList<T> items, long? total, long offset, long limit,
                      Func<long, long, Task<OffsetPage<T>>> fetch)
    {
        Items   = items;
        Total   = total;
        Offset  = offset;
        Limit   = limit;
        HasNext = total is null || (offset + items.Count) < total;
        _fetch  = fetch;
    }

    /// <summary>Collect all items across all pages into a list.</summary>
    public async Task<IReadOnlyList<T>> ToListAsync(CancellationToken ct = default)
    {
        var all = new List<T>(Items);
        var page = this;
        while (page.HasNext)
        {
            page = await page._fetch(page.Offset + page.Limit, page.Limit).ConfigureAwait(false);
            all.AddRange(page.Items);
        }
        return all;
    }

    public async IAsyncEnumerator<T> GetAsyncEnumerator(CancellationToken ct = default)
    {
        var page = this;
        while (true)
        {
            foreach (var item in page.Items)
            {
                ct.ThrowIfCancellationRequested();
                yield return item;
            }
            if (!page.HasNext) break;
            page = await page._fetch(page.Offset + page.Limit, page.Limit).ConfigureAwait(false);
        }
    }
}
`;
  }

  // ── Client ────────────────────────────────────────────────────────────────

  private renderClient(
    spec: OpenAPISpec,
    operations: ReturnType<OpenAPIParser['getOperations']>,
  ): string {
    const methods = operations.map((op) => this.renderMethod(op)).join('\n\n');
    return `// <auto-generated> Code generated by Steel Core — do not edit manually. </auto-generated>
// ${spec.info.title} v${spec.info.version}
using System.Text.Json;
using System.Text.Json.Nodes;

namespace ${this.ns};

/// <summary>${spec.info.title} API client.</summary>
public sealed class ${this.className} : IDisposable
{
    private readonly HttpTransport _http;

    /// <summary>Create a client with default retry configuration.</summary>
    public ${this.className}(string baseUrl, string? apiKey = null)
        : this(baseUrl, apiKey, RetryConfig.Default) { }

    /// <summary>Create a client with a custom retry configuration.</summary>
    public ${this.className}(string baseUrl, string? apiKey, RetryConfig retry)
    {
        var headers = new Dictionary<string, string>
        {
            ["Accept"] = "application/json",
        };
        if (apiKey is { Length: > 0 })
            headers["Authorization"] = $"Bearer {apiKey}";
        _http = new HttpTransport(baseUrl, headers, retry);
    }

${methods}

    public void Dispose() => _http.Dispose();
}
`;
  }

  private renderMethod(op: { path: string; method: string; operation: Operation }): string {
    const methodName = op.operation.operationId
      ? `${this.toPascalCase(op.operation.operationId)}Async`
      : `${this.toPascalCase(op.method)}${this.toPascalCase(op.path.replace(/[{}]/g, '').replace(/\//g, '_'))}Async`;

    const pathParams = (op.operation.parameters ?? [])
      .filter((p) => p.in === 'path')
      .map((p) => `string ${this.toCamelCase(p.name)}`);

    const queryParams = (op.operation.parameters ?? [])
      .filter((p) => p.in === 'query');

    const bodySchema = op.operation.requestBody
      ? this.parser.getRequestBodySchema(op.operation) : null;
    const bodyCsType = bodySchema?.['x-schema-name']
      ? this.toPascalCase(bodySchema['x-schema-name'])
      : bodySchema ? 'object' : null;
    const bodyParam = bodyCsType ? [`${bodyCsType}? body = null`] : [];

    const returnSchema = this.parser.getResponseSchema(op.operation);
    const rawReturn    = returnSchema?.['x-schema-name']
      ? this.toPascalCase(returnSchema['x-schema-name'])
      : returnSchema ? this.schemaToCsType(returnSchema) : null;

    const isPaginated = this.isPaginatedResponse(returnSchema);
    const itemType    = isPaginated ? this.getPaginationItemType(returnSchema!) : null;
    const hasCursor   = isPaginated && returnSchema?.properties?.['next_cursor'] != null;
    const pageClass   = hasCursor ? 'CursorPage' : 'OffsetPage';
    const returnType  = isPaginated
      ? `Task<${pageClass}<${itemType}>>`
      : rawReturn ? `Task<${rawReturn}?>` : 'Task';

    const queryParamsList = queryParams
      .map((p) => `${this.schemaToCsType(p.schema, true)} ${this.toCamelCase(p.name)} = default`);

    const ctParam = 'CancellationToken ct = default';
    const allParams = [...pathParams, ...queryParamsList, ...bodyParam, ctParam].join(', ');

    const urlPath = op.path.replace(/{(\w+)}/g, (_, k) => `{${this.toCamelCase(k)}}`);
    const doc = op.operation.summary ? `    /// <summary>${op.operation.summary}</summary>\n` : '';

    const queryDict = queryParams.map((p) => {
      const n = this.toCamelCase(p.name);
      return `            [${JSON.stringify(p.name)}] = ${n} is not default(${this.schemaToCsType(p.schema, true)}) ? (object?)${n} : null`;
    });
    const queryExpr = queryDict.length
      ? `new Dictionary<string, object?> {\n${queryDict.join(',\n')}\n        }`
      : 'null';

    if (isPaginated) {
      return hasCursor
        ? this.renderCursorMethod(methodName, doc, allParams, urlPath, queryExpr, itemType!, pageClass, returnType)
        : this.renderOffsetMethod(methodName, doc, allParams, urlPath, queryExpr, itemType!, pageClass, returnType);
    }

    const bodyArg = bodyCsType ? ', body' : '';
    if (!rawReturn) {
      return `${doc}    public async Task ${methodName}(${allParams})
    {
        await _http.RequestAsync<object>("${op.method.toUpperCase()}", $"${urlPath}", ${queryExpr}${bodyArg}, ct).ConfigureAwait(false);
    }`;
    }

    return `${doc}    public Task<${rawReturn}?> ${methodName}(${allParams})
        => _http.RequestAsync<${rawReturn}>("${op.method.toUpperCase()}", $"${urlPath}", ${queryExpr}${bodyArg}, ct);`;
  }

  private renderCursorMethod(
    name: string, doc: string, allParams: string, urlPath: string,
    queryExpr: string, itemType: string, pageClass: string, returnType: string,
  ): string {
    return `${doc}    public async ${returnType} ${name}(${allParams})
    {
        async Task<CursorPage<${itemType}>> Fetch(string? cursor)
        {
            var q = ${queryExpr} ?? new Dictionary<string, object?>();
            if (cursor is not null) q["cursor"] = cursor;
            var node  = await _http.RequestAsync<JsonObject>("GET", $"${urlPath}", q, null, ct).ConfigureAwait(false);
            var items = node?["items"]?.AsArray().Deserialize<List<${itemType}>>() ?? [];
            var next  = node?["next_cursor"]?.GetValue<string>();
            return new CursorPage<${itemType}>(items, next, Fetch);
        }
        return await Fetch(null).ConfigureAwait(false);
    }`;
  }

  private renderOffsetMethod(
    name: string, doc: string, allParams: string, urlPath: string,
    queryExpr: string, itemType: string, pageClass: string, returnType: string,
  ): string {
    return `${doc}    public async ${returnType} ${name}(${allParams})
    {
        async Task<OffsetPage<${itemType}>> Fetch(long off, long lim)
        {
            var q = ${queryExpr} ?? new Dictionary<string, object?>();
            q["offset"] = off; q["limit"] = lim;
            var node  = await _http.RequestAsync<JsonObject>("GET", $"${urlPath}", q, null, ct).ConfigureAwait(false);
            var items = node?["items"]?.AsArray().Deserialize<List<${itemType}>>() ?? [];
            var total = node?["total"]?.GetValue<long?>();
            return new OffsetPage<${itemType}>(items, total, off, lim, Fetch);
        }
        return await Fetch(0, 50).ConfigureAwait(false);
    }`;
  }

  // ── .csproj ───────────────────────────────────────────────────────────────

  private renderCsproj(spec: OpenAPISpec): string {
    return `<!-- Auto-generated by Steel Core -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12</LangVersion>
    <RootNamespace>${this.ns}</RootNamespace>
    <AssemblyName>${this.ns}</AssemblyName>
    <Version>${spec.info.version}</Version>
    <Description>${spec.info.description ?? spec.info.title + ' API client'}</Description>
  </PropertyGroup>

  <!-- No additional NuGet dependencies — uses System.Text.Json (included in .NET 8) -->
</Project>
`;
  }

  // ── Pagination detection ───────────────────────────────────────────────────

  private isPaginatedResponse(schema: SchemaObject | null): boolean {
    if (!schema?.properties) return false;
    return 'items' in schema.properties && schema.properties['items'].type === 'array';
  }

  private getPaginationItemType(schema: SchemaObject): string {
    const items = schema.properties!['items'];
    return items.items?.['x-schema-name']
      ? this.toPascalCase(items.items['x-schema-name'])
      : 'object';
  }

  // ── Type helpers ──────────────────────────────────────────────────────────

  private schemaToCsType(schema: SchemaObject, nullable = false): string {
    const base = this.baseCsType(schema);
    return nullable && !base.endsWith('?') ? `${base}?` : base;
  }

  private baseCsType(schema: SchemaObject): string {
    if (schema.$ref || schema['x-schema-name']) {
      return this.toPascalCase(schema['x-schema-name'] ?? schema.$ref!.split('/').pop()!);
    }
    if (schema.oneOf ?? schema.anyOf) return 'object';
    if (schema.nullable) return `${this.baseCsType({ ...schema, nullable: false })}?`;

    switch (schema.type) {
      case 'string':  return schema.format === 'date-time' ? 'DateTimeOffset' : 'string';
      case 'integer': return schema.format === 'int32' ? 'int' : 'long';
      case 'number':  return schema.format === 'float' ? 'float' : 'double';
      case 'boolean': return 'bool';
      case 'array':   return `List<${this.baseCsType(schema.items ?? {})}>`;
      case 'object':
        if (schema.additionalProperties && typeof schema.additionalProperties === 'object') {
          return `Dictionary<string, ${this.baseCsType(schema.additionalProperties as SchemaObject)}>`;
        }
        return 'Dictionary<string, object>';
      default: return 'object';
    }
  }

  // ── String helpers ────────────────────────────────────────────────────────

  private toPascalCase(str: string): string {
    return str
      .replace(/[-_./](\w)/g, (_, c: string) => c.toUpperCase())
      .replace(/^[a-z]/, (c) => c.toUpperCase())
      .replace(/[^a-zA-Z0-9]/g, '');
  }

  private toCamelCase(str: string): string {
    const p = this.toPascalCase(str);
    return p.charAt(0).toLowerCase() + p.slice(1);
  }
}
