import * as fs from 'fs';
import * as path from 'path';
import { OpenAPISpec, OpenAPIParser, SchemaObject, ResolvedModel, Operation } from '@steel-core/core';

export default class JavaGenerator {
  private parser!: OpenAPIParser;
  private packageName!: string;   // e.g. com.example.widgetapi
  private packageDir!: string;    // e.g. com/example/widgetapi
  private className!: string;     // e.g. WidgetApiClient

  async generate(spec: OpenAPISpec, outputDir: string): Promise<void> {
    this.parser = new OpenAPIParser();
    this.parser.parse(spec);

    const base = this.toJavaId(spec.info.title);
    this.packageName = `com.example.${base.toLowerCase()}`;
    this.packageDir  = `com/example/${base.toLowerCase()}`;
    this.className   = `${this.toPascalCase(spec.info.title)}Client`;

    const srcDir = path.join(outputDir, 'src', 'main', 'java', ...this.packageDir.split('/'));
    fs.mkdirSync(srcDir, { recursive: true });

    const models = this.parser.getModels();
    const operations = this.parser.getOperations(spec);

    // One file per model
    for (const model of models) {
      fs.writeFileSync(
        path.join(srcDir, `${this.toPascalCase(model.name)}.java`),
        this.renderModel(model),
      );
    }

    fs.writeFileSync(path.join(srcDir, 'ApiException.java'),    this.renderApiException());
    fs.writeFileSync(path.join(srcDir, 'RetryConfig.java'),     this.renderRetryConfig());
    fs.writeFileSync(path.join(srcDir, 'HttpTransport.java'),   this.renderHttpTransport());
    fs.writeFileSync(path.join(srcDir, 'CursorPage.java'),      this.renderCursorPage());
    fs.writeFileSync(path.join(srcDir, 'OffsetPage.java'),      this.renderOffsetPage());
    fs.writeFileSync(path.join(srcDir, `${this.className}.java`), this.renderClient(spec, operations));

    fs.writeFileSync(path.join(outputDir, 'pom.xml'),           this.renderPom(spec));
    fs.writeFileSync(path.join(outputDir, 'build.gradle.kts'),  this.renderGradle(spec));

    console.log(`  Created: ${models.length} model(s), ApiException, RetryConfig, HttpTransport, CursorPage, OffsetPage, ${this.className}, pom.xml, build.gradle.kts`);
  }

  // ── Model ─────────────────────────────────────────────────────────────────

  private renderModel(model: ResolvedModel): string {
    const name = this.toPascalCase(model.name);
    const schema = model.schema;

    // Enum
    if (schema.enum) {
      const values = schema.enum
        .map((v) => `    ${String(v).toUpperCase().replace(/[^A-Z0-9]/g, '_')}("${v}")`)
        .join(',\n');
      return `package ${this.packageName};

/** Auto-generated by Steel Core */
public enum ${name} {
${values};

    private final String value;
    ${name}(String value) { this.value = value; }
    public String getValue() { return value; }

    public static ${name} fromValue(String value) {
        for (${name} e : values()) {
            if (e.value.equals(value)) return e;
        }
        throw new IllegalArgumentException("Unknown ${name}: " + value);
    }
}
`;
    }

    // oneOf/anyOf → Object alias with comment
    if (schema.oneOf ?? schema.anyOf) {
      return `package ${this.packageName};

/** Auto-generated by Steel Core. Represents a union type — use Object or a sealed interface. */
public interface ${name} {}
`;
    }

    // Object → record (Java 16+)
    const props = schema.properties ?? {};
    const required = new Set(schema.required ?? []);
    const doc = schema.description ? ` * ${schema.description}\n` : '';

    const components = Object.entries(props).map(([propName, propSchema]) => {
      const javaType = this.schemaToJavaType(propSchema, !required.has(propName));
      return `    ${javaType} ${this.toCamelCase(propName)}`;
    });

    const body = components.length ? components.join(',\n') : '    // no fields';

    return `package ${this.packageName};

import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
${doc} * Auto-generated by Steel Core
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public record ${name}(
${body}
) {}
`;
  }

  // ── ApiException ──────────────────────────────────────────────────────────

  private renderApiException(): string {
    return `package ${this.packageName};

/** Thrown when the API returns a non-2xx response. */
public class ApiException extends RuntimeException {
    private final int statusCode;
    private final String body;
    private final String url;

    public ApiException(int statusCode, String body, String url) {
        super("HTTP " + statusCode + " " + url + ": " + body.substring(0, Math.min(body.length(), 200)));
        this.statusCode = statusCode;
        this.body = body;
        this.url = url;
    }

    public int getStatusCode() { return statusCode; }
    public String getBody()    { return body; }
    public String getUrl()     { return url; }

    public boolean isRetryable() {
        return statusCode == 429 || (statusCode >= 500 && statusCode < 600);
    }
}
`;
  }

  // ── RetryConfig ───────────────────────────────────────────────────────────

  private renderRetryConfig(): string {
    return `package ${this.packageName};

import java.time.Duration;

/**
 * Configuration for automatic retry behaviour.
 *
 * @param maxRetries  Number of retry attempts after the first failure. Default: 3.
 * @param baseDelay   Initial backoff delay. Default: 1s.
 * @param maxDelay    Maximum backoff delay. Default: 60s.
 * @param jitter      Add ±25% randomness to backoff. Default: true.
 */
public record RetryConfig(
    int maxRetries,
    Duration baseDelay,
    Duration maxDelay,
    boolean jitter
) {
    /** Default retry configuration: 3 retries, 1s base, 60s max, jitter enabled. */
    public static RetryConfig defaults() {
        return new RetryConfig(3, Duration.ofSeconds(1), Duration.ofSeconds(60), true);
    }

    public static RetryConfig none() {
        return new RetryConfig(0, Duration.ZERO, Duration.ZERO, false);
    }
}
`;
  }

  // ── HttpTransport ─────────────────────────────────────────────────────────

  private renderHttpTransport(): string {
    return `package ${this.packageName};

import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.Map;
import java.util.Random;
import java.util.StringJoiner;
import java.util.stream.Collectors;

/** @api private HTTP transport with automatic retry. */
class HttpTransport {
    private static final int[] RETRYABLE_STATUS = {429, 500, 502, 503, 504};
    private static final ObjectMapper MAPPER = new ObjectMapper();
    private static final Random RANDOM = new Random();

    private final String baseUrl;
    private final Map<String, String> headers;
    private final RetryConfig retry;
    private final HttpClient client;

    HttpTransport(String baseUrl, Map<String, String> headers, RetryConfig retry) {
        this.baseUrl = baseUrl.replaceAll("/$", "");
        this.headers = headers;
        this.retry   = retry;
        this.client  = HttpClient.newBuilder()
            .connectTimeout(Duration.ofSeconds(30))
            .build();
    }

    <T> T request(String method, String path, Map<String, Object> params,
                  Object body, Class<T> responseType) {
        String url = buildUrl(path, params);
        String jsonBody = null;
        if (body != null) {
            try { jsonBody = MAPPER.writeValueAsString(body); }
            catch (Exception e) { throw new RuntimeException("Failed to serialize body", e); }
        }

        Exception lastException = null;
        for (int attempt = 0; attempt <= retry.maxRetries(); attempt++) {
            if (attempt > 0) sleep(backoff(attempt - 1));

            try {
                HttpRequest.Builder reqBuilder = HttpRequest.newBuilder()
                    .uri(URI.create(url))
                    .timeout(Duration.ofSeconds(30));

                headers.forEach(reqBuilder::header);

                if (jsonBody != null) {
                    reqBuilder.header("Content-Type", "application/json")
                              .method(method, HttpRequest.BodyPublishers.ofString(jsonBody));
                } else if ("GET".equals(method) || "DELETE".equals(method)) {
                    reqBuilder.method(method, HttpRequest.BodyPublishers.noBody());
                } else {
                    reqBuilder.method(method, HttpRequest.BodyPublishers.noBody());
                }

                HttpResponse<String> resp = client.send(reqBuilder.build(),
                    HttpResponse.BodyHandlers.ofString());

                if (isRetryable(resp.statusCode()) && attempt < retry.maxRetries()) {
                    String retryAfter = resp.headers().firstValue("Retry-After").orElse(null);
                    if (retryAfter != null) {
                        sleep(Duration.ofSeconds((long) Double.parseDouble(retryAfter)));
                    }
                    lastException = new ApiException(resp.statusCode(), resp.body(), url);
                    continue;
                }

                if (resp.statusCode() < 200 || resp.statusCode() >= 300) {
                    throw new ApiException(resp.statusCode(), resp.body(), url);
                }
                if (resp.statusCode() == 204 || responseType == Void.class) return null;
                return MAPPER.readValue(resp.body(), responseType);

            } catch (ApiException e) {
                throw e;
            } catch (IOException | InterruptedException e) {
                lastException = e;
            }
        }
        throw new RuntimeException("Request failed after " + retry.maxRetries() + " retries", lastException);
    }

    /** Request returning raw JSON node for pagination. */
    com.fasterxml.jackson.databind.JsonNode requestNode(String method, String path,
                                                         Map<String, Object> params, Object body) {
        return request(method, path, params, body, com.fasterxml.jackson.databind.JsonNode.class);
    }

    private Duration backoff(int attempt) {
        long ms = Math.min(
            retry.baseDelay().toMillis() * (1L << attempt),
            retry.maxDelay().toMillis()
        );
        if (retry.jitter()) ms = (long) (ms * (0.75 + RANDOM.nextDouble() * 0.5));
        return Duration.ofMillis(ms);
    }

    private static boolean isRetryable(int status) {
        for (int s : RETRYABLE_STATUS) if (s == status) return true;
        return false;
    }

    private static void sleep(Duration d) {
        try { Thread.sleep(d.toMillis()); }
        catch (InterruptedException e) { Thread.currentThread().interrupt(); }
    }

    private static String buildUrl(String path, Map<String, Object> params) {
        if (params == null || params.isEmpty()) return path;
        String qs = params.entrySet().stream()
            .filter(e -> e.getValue() != null)
            .map(e -> encode(e.getKey()) + "=" + encode(String.valueOf(e.getValue())))
            .collect(Collectors.joining("&"));
        return qs.isEmpty() ? path : path + "?" + qs;
    }

    private static String encode(String s) {
        return URLEncoder.encode(s, StandardCharsets.UTF_8);
    }
}
`;
  }

  // ── CursorPage ────────────────────────────────────────────────────────────

  private renderCursorPage(): string {
    return `package ${this.packageName};

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.function.Function;

/**
 * A cursor-paginated result set. Implements {@link Iterable} for transparent auto-pagination.
 *
 * <pre>{@code
 * for (Widget w : client.listWidgets()) {
 *     System.out.println(w.name());
 * }
 * }</pre>
 */
public class CursorPage<T> implements Iterable<T> {
    private final List<T> items;
    private final String nextCursor;
    private final boolean hasNext;
    private final Function<String, CursorPage<T>> fetch;

    public CursorPage(List<T> items, String nextCursor, Function<String, CursorPage<T>> fetch) {
        this.items      = items != null ? items : List.of();
        this.nextCursor = nextCursor;
        this.hasNext    = nextCursor != null;
        this.fetch      = fetch;
    }

    public List<T> getItems()       { return items; }
    public String  getNextCursor()  { return nextCursor; }
    public boolean hasNext()        { return hasNext; }

    /** Collect all items across all pages into a single list. */
    public List<T> toList() {
        List<T> all = new ArrayList<>(items);
        CursorPage<T> page = this;
        while (page.hasNext) {
            page = page.fetch.apply(page.nextCursor);
            all.addAll(page.items);
        }
        return all;
    }

    @Override
    public Iterator<T> iterator() {
        return new Iterator<>() {
            private CursorPage<T> current = CursorPage.this;
            private int index = 0;

            @Override public boolean hasNext() {
                return index < current.items.size() || current.hasNext;
            }

            @Override public T next() {
                if (index >= current.items.size()) {
                    if (!current.hasNext) throw new NoSuchElementException();
                    current = current.fetch.apply(current.nextCursor);
                    index   = 0;
                }
                return current.items.get(index++);
            }
        };
    }
}
`;
  }

  // ── OffsetPage ────────────────────────────────────────────────────────────

  private renderOffsetPage(): string {
    return `package ${this.packageName};

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.function.BiFunction;

/**
 * An offset/limit-paginated result set. Implements {@link Iterable} for transparent auto-pagination.
 */
public class OffsetPage<T> implements Iterable<T> {
    private final List<T> items;
    private final Long total;
    private final long offset;
    private final long limit;
    private final boolean hasNext;
    private final BiFunction<Long, Long, OffsetPage<T>> fetch;

    public OffsetPage(List<T> items, Long total, long offset, long limit,
                      BiFunction<Long, Long, OffsetPage<T>> fetch) {
        this.items   = items != null ? items : List.of();
        this.total   = total;
        this.offset  = offset;
        this.limit   = limit;
        this.hasNext = total == null || (offset + items.size()) < total;
        this.fetch   = fetch;
    }

    public List<T> getItems()  { return items; }
    public Long    getTotal()  { return total; }
    public long    getOffset() { return offset; }
    public long    getLimit()  { return limit; }
    public boolean hasNext()   { return hasNext; }

    /** Collect all items across all pages into a single list. */
    public List<T> toList() {
        List<T> all = new ArrayList<>(items);
        OffsetPage<T> page = this;
        while (page.hasNext) {
            page = page.fetch.apply(page.offset + page.limit, page.limit);
            all.addAll(page.items);
        }
        return all;
    }

    @Override
    public Iterator<T> iterator() {
        return new Iterator<>() {
            private OffsetPage<T> current = OffsetPage.this;
            private int index = 0;

            @Override public boolean hasNext() {
                return index < current.items.size() || current.hasNext;
            }

            @Override public T next() {
                if (index >= current.items.size()) {
                    if (!current.hasNext) throw new NoSuchElementException();
                    current = current.fetch.apply(current.offset + current.limit, current.limit);
                    index   = 0;
                }
                return current.items.get(index++);
            }
        };
    }
}
`;
  }

  // ── Client ────────────────────────────────────────────────────────────────

  private renderClient(
    spec: OpenAPISpec,
    operations: ReturnType<OpenAPIParser['getOperations']>,
  ): string {
    const methods = operations.map((op) => this.renderMethod(op)).join('\n\n');
    const pkg = this.packageName;

    return `package ${pkg};

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * ${spec.info.title} v${spec.info.version} — auto-generated by Steel Core.
 */
public class ${this.className} {
    private final HttpTransport http;

    /** Create a client with default retry configuration. */
    public ${this.className}(String baseUrl, String apiKey) {
        this(baseUrl, apiKey, RetryConfig.defaults());
    }

    /** Create a client with custom retry configuration. */
    public ${this.className}(String baseUrl, String apiKey, RetryConfig retry) {
        Map<String, String> headers = new HashMap<>();
        headers.put("Accept", "application/json");
        if (apiKey != null && !apiKey.isEmpty()) {
            headers.put("Authorization", "Bearer " + apiKey);
        }
        this.http = new HttpTransport(baseUrl, headers, retry);
    }

${methods}
}
`;
  }

  private renderMethod(op: { path: string; method: string; operation: Operation }): string {
    const methodName = op.operation.operationId
      ? this.toCamelCase(op.operation.operationId)
      : `${op.method.toLowerCase()}${this.toPascalCase(op.path.replace(/[{}]/g, '').replace(/\//g, '_'))}`;

    const pathParams = (op.operation.parameters ?? [])
      .filter((p) => p.in === 'path')
      .map((p) => `String ${this.toCamelCase(p.name)}`);

    const queryParams = (op.operation.parameters ?? [])
      .filter((p) => p.in === 'query');

    const bodySchema = op.operation.requestBody
      ? this.parser.getRequestBodySchema(op.operation) : null;
    const bodyJavaType = bodySchema?.['x-schema-name']
      ? this.toPascalCase(bodySchema['x-schema-name'])
      : bodySchema ? 'Object' : null;
    const bodyParam = bodyJavaType ? [`${bodyJavaType} body`] : [];

    const returnSchema = this.parser.getResponseSchema(op.operation);
    const rawReturn = returnSchema?.['x-schema-name']
      ? this.toPascalCase(returnSchema['x-schema-name'])
      : returnSchema ? this.schemaToJavaType(returnSchema, false) : null;

    const isPaginated = this.isPaginatedResponse(returnSchema);
    const itemType = isPaginated ? this.getPaginationItemType(returnSchema!) : null;
    const hasCursor = isPaginated && returnSchema?.properties?.['next_cursor'] != null;
    const pageClass = hasCursor ? 'CursorPage' : 'OffsetPage';
    const returnType = isPaginated ? `${pageClass}<${itemType}>` : rawReturn ?? 'void';

    const queryJavaParams = queryParams.map((p) => {
      const t = this.schemaToJavaType(p.schema, true);
      return `${t} ${this.toCamelCase(p.name)}`;
    });

    const allParams = [...pathParams, ...queryJavaParams, ...bodyParam].join(', ');
    const urlPath = op.path.replace(/{(\w+)}/g, (_, k) => `" + ${this.toCamelCase(k)} + "`);
    const urlExpr = `"${urlPath}"`;
    const doc = op.operation.summary ? `    /** ${op.operation.summary} */\n` : '';

    // Build params map
    const queryMapLines = queryParams.map((p) => {
      const jName = this.toCamelCase(p.name);
      return `        if (${jName} != null) params.put("${p.name}", ${jName});`;
    });
    const paramsBlock = queryParams.length
      ? `        Map<String, Object> params = new HashMap<>();\n${queryMapLines.join('\n')}\n`
      : '        Map<String, Object> params = Map.of();\n';
    const paramsArg = 'params';
    const bodyArg = bodyJavaType ? 'body' : 'null';

    if (isPaginated) {
      return hasCursor
        ? this.renderCursorMethod(methodName, doc, allParams, urlExpr, paramsBlock, itemType!, returnType)
        : this.renderOffsetMethod(methodName, doc, allParams, urlExpr, paramsBlock, itemType!, returnType);
    }

    if (!rawReturn) {
      return `${doc}    public void ${methodName}(${allParams}) {
        Map<String, Object> params = Map.of();
        http.request("${op.method.toUpperCase()}", ${urlExpr}, ${paramsArg}, ${bodyArg}, Void.class);
    }`;
    }

    return `${doc}    public ${returnType} ${methodName}(${allParams}) {
${paramsBlock}        return http.request("${op.method.toUpperCase()}", ${urlExpr}, ${paramsArg}, ${bodyArg}, ${rawReturn}.class);
    }`;
  }

  private renderCursorMethod(
    name: string, doc: string, params: string, urlExpr: string,
    paramsBlock: string, itemType: string, returnType: string,
  ): string {
    return `${doc}    public ${returnType} ${name}(${params ? params + ', ' : ''}Long limit, String cursor) {
        java.util.function.Function<String, CursorPage<${itemType}>> fetch = (cur) -> {
${paramsBlock}            if (limit != null) params.put("limit", limit);
            if (cur   != null) params.put("cursor", cur);
            var node  = http.requestNode("GET", ${urlExpr}, params, null);
            var items = parseList(node.path("items"), ${itemType}.class);
            var next  = node.path("next_cursor").isNull() ? null : node.path("next_cursor").asText(null);
            return new CursorPage<>(items, next, fetch);
        };
        return fetch.apply(cursor);
    }`;
  }

  private renderOffsetMethod(
    name: string, doc: string, params: string, urlExpr: string,
    paramsBlock: string, itemType: string, returnType: string,
  ): string {
    return `${doc}    public ${returnType} ${name}(${params ? params + ', ' : ''}Long limit, Long offset) {
        java.util.function.BiFunction<Long, Long, OffsetPage<${itemType}>> fetch = (off, lim) -> {
${paramsBlock}            if (lim != null) params.put("limit", lim);
            params.put("offset", off != null ? off : 0);
            var node  = http.requestNode("GET", ${urlExpr}, params, null);
            var items = parseList(node.path("items"), ${itemType}.class);
            var total = node.path("total").isMissingNode() ? null : node.path("total").longValue();
            return new OffsetPage<>(items, total, off != null ? off : 0, lim != null ? lim : 50, fetch);
        };
        return fetch.apply(offset != null ? offset : 0L, limit != null ? limit : 50L);
    }

    @SuppressWarnings("unchecked")
    private <T> java.util.List<T> parseList(com.fasterxml.jackson.databind.JsonNode node, Class<T> type) {
        try {
            return HttpTransport.MAPPER.readerForListOf(type).readValue(node);
        } catch (Exception e) {
            return java.util.List.of();
        }
    }`;
  }

  // ── pom.xml ───────────────────────────────────────────────────────────────

  private renderPom(spec: OpenAPISpec): string {
    const artifactId = this.toJavaId(spec.info.title).toLowerCase();
    return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Auto-generated by Steel Core -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.example</groupId>
  <artifactId>${artifactId}</artifactId>
  <version>${spec.info.version}</version>
  <packaging>jar</packaging>

  <properties>
    <java.version>17</java.version>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <jackson.version>2.17.0</jackson.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>\${jackson.version}</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-jsr310</artifactId>
      <version>\${jackson.version}</version>
    </dependency>

    <!-- Test -->
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>5.10.0</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
`;
  }

  // ── build.gradle.kts ──────────────────────────────────────────────────────

  private renderGradle(spec: OpenAPISpec): string {
    const artifactId = this.toJavaId(spec.info.title).toLowerCase();
    return `// Auto-generated by Steel Core
plugins {
    java
}

group   = "com.example"
version = "${spec.info.version}"

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.fasterxml.jackson.core:jackson-databind:2.17.0")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.0")
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
}

tasks.test { useJUnitPlatform() }
`;
  }

  // ── Pagination detection ───────────────────────────────────────────────────

  private isPaginatedResponse(schema: SchemaObject | null): boolean {
    if (!schema?.properties) return false;
    return 'items' in schema.properties && schema.properties['items'].type === 'array';
  }

  private getPaginationItemType(schema: SchemaObject): string {
    const items = schema.properties!['items'];
    return items.items?.['x-schema-name']
      ? this.toPascalCase(items.items['x-schema-name'])
      : 'Object';
  }

  // ── Type mapping ──────────────────────────────────────────────────────────

  private schemaToJavaType(schema: SchemaObject, nullable: boolean): string {
    const base = this.baseJavaType(schema);
    // Use boxed types for nullable fields
    if (nullable) {
      const boxed: Record<string, string> = { int: 'Integer', long: 'Long', double: 'Double', boolean: 'Boolean', float: 'Float' };
      return boxed[base] ?? base;
    }
    return base;
  }

  private baseJavaType(schema: SchemaObject): string {
    if (schema.$ref || schema['x-schema-name']) {
      return this.toPascalCase(schema['x-schema-name'] ?? schema.$ref!.split('/').pop()!);
    }
    if (schema.oneOf ?? schema.anyOf) return 'Object';
    if (schema.nullable) return this.schemaToJavaType({ ...schema, nullable: false }, true);

    switch (schema.type) {
      case 'string':  return 'String';
      case 'integer': return schema.format === 'int32' ? 'int' : 'long';
      case 'number':  return schema.format === 'float' ? 'float' : 'double';
      case 'boolean': return 'boolean';
      case 'array':   return `List<${this.schemaToJavaType(schema.items ?? {}, false)}>`;
      case 'object':
        if (schema.additionalProperties && typeof schema.additionalProperties === 'object') {
          return `Map<String, ${this.schemaToJavaType(schema.additionalProperties as SchemaObject, false)}>`;
        }
        return 'Map<String, Object>';
      default: return 'Object';
    }
  }

  // ── String helpers ────────────────────────────────────────────────────────

  private toPascalCase(str: string): string {
    return str
      .replace(/[-_./](\w)/g, (_, c: string) => c.toUpperCase())
      .replace(/^[a-z]/, (c) => c.toUpperCase())
      .replace(/[^a-zA-Z0-9]/g, '');
  }

  private toCamelCase(str: string): string {
    const p = this.toPascalCase(str);
    return p.charAt(0).toLowerCase() + p.slice(1);
  }

  private toJavaId(title: string): string {
    return title.replace(/[^a-zA-Z0-9]/g, '').replace(/^[0-9]/, '_$&');
  }
}
