import * as fs from 'fs';
import * as path from 'path';
import { OpenAPISpec, OpenAPIParser, SchemaObject, ResolvedModel, Operation } from '@steel-core/core';

export default class RubyGenerator {
  private parser!: OpenAPIParser;
  private gemName!: string;
  private moduleName!: string;

  async generate(spec: OpenAPISpec, outputDir: string): Promise<void> {
    fs.mkdirSync(outputDir, { recursive: true });
    this.parser = new OpenAPIParser();
    this.parser.parse(spec);
    this.gemName = this.toGemName(spec.info.title);
    this.moduleName = this.toPascalCase(spec.info.title);

    const models = this.parser.getModels();
    const operations = this.parser.getOperations(spec);

    const libDir = path.join(outputDir, 'lib', this.gemName);
    fs.mkdirSync(libDir, { recursive: true });

    fs.writeFileSync(path.join(libDir, 'version.rb'),        this.renderVersion(spec));
    fs.writeFileSync(path.join(libDir, 'errors.rb'),         this.renderErrors());
    fs.writeFileSync(path.join(libDir, 'http.rb'),           this.renderHttp());
    fs.writeFileSync(path.join(libDir, 'pagination.rb'),     this.renderPagination());
    fs.writeFileSync(path.join(libDir, 'models.rb'),         this.renderModels(models));
    fs.writeFileSync(path.join(libDir, 'client.rb'),         this.renderClient(spec, operations));
    fs.writeFileSync(path.join(outputDir, 'lib', `${this.gemName}.rb`), this.renderEntrypoint(spec));
    fs.writeFileSync(path.join(outputDir, `${this.gemName}.gemspec`),   this.renderGemspec(spec));
    fs.writeFileSync(path.join(outputDir, 'Gemfile'),                    this.renderGemfile());

    console.log(`  Created: lib/${this.gemName}/{version,errors,http,pagination,models,client}.rb + gemspec`);
  }

  // ── version.rb ────────────────────────────────────────────────────────────

  private renderVersion(spec: OpenAPISpec): string {
    return `# frozen_string_literal: true
# Code generated by Steel Core — do not edit manually.

module ${this.moduleName}
  VERSION = "${spec.info.version}".freeze
end
`;
  }

  // ── errors.rb ─────────────────────────────────────────────────────────────

  private renderErrors(): string {
    return `# frozen_string_literal: true
# Code generated by Steel Core — do not edit manually.

module ${this.moduleName}
  # Base error class for all API errors.
  class Error < StandardError; end

  # Raised when the server returns a non-2xx response.
  class APIError < Error
    attr_reader :status, :body, :url

    def initialize(status:, body:, url:)
      @status = status
      @body   = body
      @url    = url
      super("HTTP #{status} #{url}: #{body.to_s.slice(0, 200)}")
    end
  end

  # Raised when the server returns 429.
  class RateLimitError < APIError; end

  # Raised when the request times out.
  class TimeoutError < Error; end

  # Raised when the server returns 401 or 403.
  class AuthError < APIError; end
end
`;
  }

  // ── http.rb ───────────────────────────────────────────────────────────────

  private renderHttp(): string {
    return `# frozen_string_literal: true
# Code generated by Steel Core — do not edit manually.

require "net/http"
require "uri"
require "json"

module ${this.moduleName}
  # Configuration for automatic retry behaviour.
  RetryConfig = Struct.new(:max_retries, :base_delay, :max_delay, :jitter, keyword_init: true) do
    def initialize(max_retries: 3, base_delay: 1.0, max_delay: 60.0, jitter: true)
      super
    end
  end

  RETRYABLE_STATUS = [429, 500, 502, 503, 504].freeze
  RETRYABLE_ERRORS = [Net::OpenTimeout, Net::ReadTimeout, Errno::ECONNRESET, EOFError].freeze

  # @api private
  class HttpTransport
    def initialize(base_url:, headers:, timeout:, retry_config:)
      @uri          = URI.parse(base_url.chomp("/"))
      @headers      = headers
      @timeout      = timeout
      @retry_config = retry_config
    end

    def request(method, path, params: nil, body: nil)
      last_error = nil

      (@retry_config.max_retries + 1).times do |attempt|
        sleep(_backoff(attempt - 1)) if attempt > 0

        begin
          resp = _execute(method, path, params: params, body: body)

          if RETRYABLE_STATUS.include?(resp.code.to_i) && attempt < @retry_config.max_retries
            if (ra = resp["Retry-After"])
              sleep(ra.to_f)
              next
            end
            last_error = _build_error(resp, path)
            next
          end

          _raise_for_status!(resp, path)
          return resp.code == "204" ? nil : JSON.parse(resp.body, symbolize_names: false)
        rescue *RETRYABLE_ERRORS => e
          last_error = e
          next if attempt < @retry_config.max_retries
          raise TimeoutError, e.message
        end
      end

      raise last_error if last_error
    end

    private

    def _execute(method, path, params:, body:)
      uri = @uri.dup
      uri.path = (@uri.path + path).gsub(%r{/+}, "/")
      uri.query = URI.encode_www_form(params.compact) if params&.any?

      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl     = uri.scheme == "https"
      http.open_timeout = @timeout
      http.read_timeout = @timeout

      req_class = {
        "GET"    => Net::HTTP::Get,
        "POST"   => Net::HTTP::Post,
        "PUT"    => Net::HTTP::Put,
        "PATCH"  => Net::HTTP::Patch,
        "DELETE" => Net::HTTP::Delete,
      }.fetch(method.upcase)

      req = req_class.new(uri)
      @headers.each { |k, v| req[k] = v }
      if body
        req.body         = body.to_json
        req["Content-Type"] = "application/json"
      end

      http.request(req)
    end

    def _backoff(attempt)
      delay = [@retry_config.base_delay * (2**attempt), @retry_config.max_delay].min
      @retry_config.jitter ? delay * (0.75 + rand * 0.5) : delay
    end

    def _raise_for_status!(resp, path)
      code = resp.code.to_i
      return if code >= 200 && code < 300

      err = _build_error(resp, path)
      raise err
    end

    def _build_error(resp, _path)
      klass = case resp.code.to_i
              when 429 then RateLimitError
              when 401, 403 then AuthError
              else APIError
              end
      klass.new(status: resp.code.to_i, body: resp.body.to_s, url: @uri.to_s)
    end
  end
end
`;
  }

  // ── pagination.rb ─────────────────────────────────────────────────────────

  private renderPagination(): string {
    return `# frozen_string_literal: true
# Code generated by Steel Core — do not edit manually.

module ${this.moduleName}
  # Cursor-based page. Implements Enumerable for transparent auto-pagination.
  #
  # @example
  #   client.list_widgets.each { |w| puts w["name"] }
  #   all = client.list_widgets.to_a
  class CursorPage
    include Enumerable

    attr_reader :items, :next_cursor, :has_next

    def initialize(items:, next_cursor:, fetch:)
      @items       = items
      @next_cursor = next_cursor
      @has_next    = !next_cursor.nil?
      @fetch       = fetch
    end

    # Yields every item across all pages, fetching lazily.
    def each(&block)
      return enum_for(:each) unless block

      page = self
      loop do
        page.items.each(&block)
        break unless page.next_cursor

        page = page.@fetch.call(page.next_cursor)
      end
    end
  end

  # Offset/limit-based page. Implements Enumerable for transparent auto-pagination.
  #
  # @example
  #   client.list_widgets(limit: 10).each { |w| puts w["name"] }
  class OffsetPage
    include Enumerable

    attr_reader :items, :total, :offset, :limit, :has_next

    def initialize(items:, total:, offset:, limit:, fetch:)
      @items   = items
      @total   = total
      @offset  = offset
      @limit   = limit
      @has_next = total.nil? || (offset + items.length) < total
      @fetch   = fetch
    end

    # Yields every item across all pages, fetching lazily.
    def each(&block)
      return enum_for(:each) unless block

      page = self
      loop do
        page.items.each(&block)
        break unless page.has_next

        page = page.@fetch.call(page.offset + page.limit, page.limit)
      end
    end
  end
end
`;
  }

  // ── models.rb ─────────────────────────────────────────────────────────────

  private renderModels(models: ResolvedModel[]): string {
    const classes = models.map((m) => this.renderModel(m.name, m.schema)).join('\n\n');
    return `# frozen_string_literal: true
# Code generated by Steel Core — do not edit manually.

module ${this.moduleName}
  module Models
${classes}
  end
end
`;
  }

  private renderModel(name: string, schema: SchemaObject): string {
    const className = this.toPascalCase(name);

    // Enum → module with constants
    if (schema.enum) {
      const consts = schema.enum
        .map((v) => `      ${String(v).toUpperCase().replace(/[^A-Z0-9]/g, '_')} = ${JSON.stringify(v)}.freeze`)
        .join('\n');
      return `    # ${className} enum values\n    module ${className}\n${consts}\n    end`;
    }

    // oneOf/anyOf → comment-only marker (Ruby is duck-typed)
    if (schema.oneOf ?? schema.anyOf) {
      const variants = (schema.oneOf ?? schema.anyOf)!.map((s) => this.schemaToRubyType(s)).join(', ');
      return `    # ${className} is one of: ${variants}\n    ${className} = ::Object`;
    }

    // Object → Struct with keyword_init
    const props = schema.properties ?? {};
    const required = new Set(schema.required ?? []);
    const allProps = Object.keys(props);
    const doc = schema.description ? `    # ${schema.description}\n` : '';

    if (!allProps.length) {
      return `${doc}    ${className} = ::Struct.new(keyword_init: true)`;
    }

    const members = allProps.map((p) => `:${this.toSnakeCase(p)}`).join(', ');
    const validations = [...required]
      .map((p) => `      raise ArgumentError, "${this.toSnakeCase(p)} is required" if ${this.toSnakeCase(p)}.nil?`)
      .join('\n');

    return `${doc}    ${className} = ::Struct.new(${members}, keyword_init: true) do
      def initialize(**kwargs)
        super
${validations || '        # no required fields'}
      end
    end`;
  }

  // ── client.rb ─────────────────────────────────────────────────────────────

  private renderClient(
    spec: OpenAPISpec,
    operations: ReturnType<OpenAPIParser['getOperations']>,
  ): string {
    const methods = operations.map((op) => this.renderMethod(op)).join('\n\n');

    return `# frozen_string_literal: true
# Code generated by Steel Core — do not edit manually.
# ${spec.info.title} v${spec.info.version}

module ${this.moduleName}
  class Client
    # @param base_url  [String]      API base URL
    # @param api_key   [String, nil] Bearer token
    # @param timeout   [Float]       Request timeout in seconds (default 30)
    # @param retry     [RetryConfig] Retry configuration
    def initialize(base_url:, api_key: nil, timeout: 30.0, retry: RetryConfig.new)
      headers = { "Accept" => "application/json" }
      headers["Authorization"] = "Bearer #{api_key}" if api_key

      @http = HttpTransport.new(
        base_url: base_url,
        headers: headers,
        timeout: timeout,
        retry_config: binding.local_variable_get(:retry),
      )
    end

${methods}
  end
end
`;
  }

  private renderMethod(op: { path: string; method: string; operation: Operation }): string {
    const name = op.operation.operationId
      ? this.toSnakeCase(op.operation.operationId)
      : `${op.method}_${this.toSnakeCase(op.path.replace(/[{}]/g, '').replace(/\//g, '_'))}`;

    const pathParams = (op.operation.parameters ?? [])
      .filter((p) => p.in === 'path')
      .map((p) => this.toSnakeCase(p.name));

    const queryParams = (op.operation.parameters ?? [])
      .filter((p) => p.in === 'query')
      .map((p) => `${this.toSnakeCase(p.name)}: nil`);

    const bodySchema = op.operation.requestBody
      ? this.parser.getRequestBodySchema(op.operation) : null;
    const bodyParam = bodySchema ? ['body: nil'] : [];

    const returnSchema = this.parser.getResponseSchema(op.operation);
    const isPaginated = this.isPaginatedResponse(returnSchema);
    const itemType = isPaginated ? this.getPaginationItemType(returnSchema!) : null;
    const hasCursor = isPaginated && returnSchema?.properties?.['next_cursor'] != null;

    const allKwargs = [...queryParams, ...bodyParam].join(', ');
    const kwargSig = allKwargs ? `, ${allKwargs}` : '';
    const positionalSig = pathParams.join(', ');
    const sig = [positionalSig, kwargSig ? kwargSig.slice(2) : ''].filter(Boolean).join(', ');

    const urlPath = op.path.replace(/{(\w+)}/g, (_, k) => `\#{${this.toSnakeCase(k)}}`);
    const doc = op.operation.summary ? `    # ${op.operation.summary}\n` : '';

    const queryKeys = (op.operation.parameters ?? [])
      .filter((p) => p.in === 'query')
      .map((p) => `"${p.name}" => ${this.toSnakeCase(p.name)}`);
    const paramsExpr = queryKeys.length
      ? `{ ${queryKeys.join(', ')} }.compact`
      : 'nil';

    if (isPaginated) {
      return hasCursor
        ? this.renderCursorMethod(name, doc, sig, urlPath, paramsExpr, hasCursor, itemType!)
        : this.renderOffsetMethod(name, doc, sig, urlPath, paramsExpr, itemType!);
    }

    const bodyArg = bodySchema ? ', body: body' : '';
    return `${doc}    def ${name}(${sig})
      @http.request("${op.method.toUpperCase()}", "${urlPath}", params: ${paramsExpr}${bodyArg})
    end`;
  }

  private renderCursorMethod(
    name: string, doc: string, sig: string, urlPath: string,
    paramsExpr: string, _hasCursor: boolean, _itemType: string,
  ): string {
    const fullSig = sig ? `${sig}, limit: 50, cursor: nil` : 'limit: 50, cursor: nil';
    return `${doc}    def ${name}(${fullSig})
      fetch = ->(cur) {
        params = ${paramsExpr} || {}
        params = params.merge("limit" => limit, "cursor" => cur).compact
        raw = @http.request("GET", "${urlPath}", params: params)
        CursorPage.new(
          items: raw.fetch("items", []),
          next_cursor: raw["next_cursor"],
          fetch: fetch,
        )
      }
      fetch.call(cursor)
    end`;
  }

  private renderOffsetMethod(
    name: string, doc: string, sig: string, urlPath: string,
    paramsExpr: string, _itemType: string,
  ): string {
    const fullSig = sig ? `${sig}, limit: 50, offset: 0` : 'limit: 50, offset: 0';
    return `${doc}    def ${name}(${fullSig})
      fetch = ->(off, lim) {
        params = (${paramsExpr} || {}).merge("limit" => lim, "offset" => off)
        raw = @http.request("GET", "${urlPath}", params: params)
        OffsetPage.new(
          items: raw.fetch("items", []),
          total: raw["total"],
          offset: off,
          limit: lim,
          fetch: fetch,
        )
      }
      fetch.call(offset, limit)
    end`;
  }

  // ── entrypoint + gemspec ──────────────────────────────────────────────────

  private renderEntrypoint(spec: OpenAPISpec): string {
    return `# frozen_string_literal: true
# Code generated by Steel Core — do not edit manually.

require_relative "${this.gemName}/version"
require_relative "${this.gemName}/errors"
require_relative "${this.gemName}/http"
require_relative "${this.gemName}/pagination"
require_relative "${this.gemName}/models"
require_relative "${this.gemName}/client"

# ${spec.info.title} Ruby SDK — auto-generated by Steel Core
module ${this.moduleName}
  # @param base_url [String]
  # @param api_key  [String, nil]
  # @param **opts   passed to Client#initialize
  def self.new(base_url:, api_key: nil, **opts)
    Client.new(base_url: base_url, api_key: api_key, **opts)
  end
end
`;
  }

  private renderGemspec(spec: OpenAPISpec): string {
    return `# frozen_string_literal: true
# Code generated by Steel Core — do not edit manually.

require_relative "lib/${this.gemName}/version"

Gem::Specification.new do |spec|
  spec.name        = "${this.gemName}"
  spec.version     = ${this.moduleName}::VERSION
  spec.summary     = "${spec.info.title} Ruby SDK"
  spec.description = "${spec.info.description ?? spec.info.title + ' API client'}"
  spec.authors     = ["Steel Core"]
  spec.license     = "MIT"

  spec.required_ruby_version = ">= 3.0.0"
  spec.files = Dir["lib/**/*.rb", "*.gemspec", "README.md"]

  # No runtime dependencies — uses only stdlib net/http
end
`;
  }

  private renderGemfile(): string {
    return `# frozen_string_literal: true

source "https://rubygems.org"

gemspec
`;
  }

  // ── Pagination detection ──────────────────────────────────────────────────

  private isPaginatedResponse(schema: SchemaObject | null): boolean {
    if (!schema?.properties) return false;
    return 'items' in schema.properties && schema.properties['items'].type === 'array';
  }

  private getPaginationItemType(schema: SchemaObject): string {
    const items = schema.properties!['items'];
    return items.items?.['x-schema-name'] ?? 'Hash';
  }

  // ── Type helpers ──────────────────────────────────────────────────────────

  private schemaToRubyType(schema: SchemaObject): string {
    if (schema.$ref || schema['x-schema-name']) {
      return `Models::${this.toPascalCase(schema['x-schema-name'] ?? schema.$ref!.split('/').pop()!)}`;
    }
    switch (schema.type) {
      case 'string':  return 'String';
      case 'integer': return 'Integer';
      case 'number':  return 'Float';
      case 'boolean': return 'TrueClass/FalseClass';
      case 'array':   return `Array<${schema.items ? this.schemaToRubyType(schema.items) : 'Object'}>`;
      case 'object':  return 'Hash';
      default:        return 'Object';
    }
  }

  // ── String helpers ────────────────────────────────────────────────────────

  private toPascalCase(str: string): string {
    return str
      .replace(/[-_./](\w)/g, (_, c: string) => c.toUpperCase())
      .replace(/^[a-z]/, (c) => c.toUpperCase())
      .replace(/[^a-zA-Z0-9]/g, '');
  }

  private toSnakeCase(str: string): string {
    return str
      .replace(/([A-Z])/g, '_$1')
      .toLowerCase()
      .replace(/^_/, '')
      .replace(/[^a-z0-9_]/g, '_')
      .replace(/_+/g, '_');
  }

  private toGemName(title: string): string {
    return title.toLowerCase().replace(/[^a-z0-9]/g, '_').replace(/_+/g, '_').replace(/^_|_$/, '');
  }
}
