import * as fs from 'fs';
import * as path from 'path';
import { OpenAPISpec, OpenAPIParser, SchemaObject, ResolvedModel, Operation } from '@steel-core/core';

export default class PhpGenerator {
  private parser!: OpenAPIParser;
  private ns!: string;       // PHP namespace, e.g. WidgetApi
  private className!: string; // e.g. WidgetApiClient

  async generate(spec: OpenAPISpec, outputDir: string): Promise<void> {
    fs.mkdirSync(outputDir, { recursive: true });
    this.parser = new OpenAPIParser();
    this.parser.parse(spec);
    this.ns        = this.toPascalCase(spec.info.title);
    this.className = `${this.ns}Client`;

    const models     = this.parser.getModels();
    const operations = this.parser.getOperations(spec);

    const srcDir = path.join(outputDir, 'src');
    fs.mkdirSync(srcDir, { recursive: true });

    // One file per model
    for (const model of models) {
      fs.writeFileSync(
        path.join(srcDir, `${this.toPascalCase(model.name)}.php`),
        this.renderModel(model),
      );
    }

    fs.writeFileSync(path.join(srcDir, 'ApiException.php'),  this.renderApiException());
    fs.writeFileSync(path.join(srcDir, 'RetryConfig.php'),   this.renderRetryConfig());
    fs.writeFileSync(path.join(srcDir, 'HttpTransport.php'), this.renderHttpTransport());
    fs.writeFileSync(path.join(srcDir, 'CursorPage.php'),    this.renderCursorPage());
    fs.writeFileSync(path.join(srcDir, 'OffsetPage.php'),    this.renderOffsetPage());
    fs.writeFileSync(path.join(srcDir, `${this.className}.php`), this.renderClient(spec, operations));

    fs.writeFileSync(path.join(outputDir, 'composer.json'), this.renderComposer(spec));

    console.log(`  Created: src/{${models.map((m) => this.toPascalCase(m.name)).join(',')},...,${this.className}}.php + composer.json`);
  }

  // ── Model ─────────────────────────────────────────────────────────────────

  private renderModel(model: ResolvedModel): string {
    const name   = this.toPascalCase(model.name);
    const schema = model.schema;

    // Enum → backed enum (PHP 8.1+)
    if (schema.enum) {
      const cases = schema.enum
        .map((v) => `    case ${this.toPascalCase(String(v))} = '${v}';`)
        .join('\n');
      return `<?php
// @generated Code generated by Steel Core — do not edit manually.
declare(strict_types=1);

namespace ${this.ns};

enum ${name}: string
{
${cases}
}
`;
    }

    // oneOf/anyOf → interface
    if (schema.oneOf ?? schema.anyOf) {
      const variants = (schema.oneOf ?? schema.anyOf)!.map((s) => this.schemaToPhpType(s)).join('|');
      return `<?php
// @generated Code generated by Steel Core — do not edit manually.
declare(strict_types=1);

namespace ${this.ns};

/** Union type: ${variants} */
interface ${name} {}
`;
    }

    // Object → readonly class (PHP 8.2+)
    const props    = schema.properties ?? {};
    const required = new Set(schema.required ?? []);
    const doc      = schema.description ? ` * ${schema.description}\n` : '';

    const ctorParams = Object.entries(props).map(([propName, propSchema]) => {
      const phpType  = this.schemaToPhpType(propSchema, !required.has(propName));
      const propId   = $camel(propName);
      const nullable = !required.has(propName) && !phpType.startsWith('?') ? '' : '';
      const default_ = !required.has(propName) ? ' = null' : '';
      return `        public readonly ${phpType} $${propId}${default_},`;
    });

    const body = ctorParams.length ? ctorParams.join('\n') : '        // no properties';

    return `<?php
// @generated Code generated by Steel Core — do not edit manually.
declare(strict_types=1);

namespace ${this.ns};

/**
${doc} * @generated
 */
readonly class ${name}
{
    public function __construct(
${body}
    ) {}

    /** Create from a decoded JSON array. */
    public static function fromArray(array $data): self
    {
        return new self(
${Object.entries(props).map(([p, s]) => {
  const id = $camel(p);
  const val = this.fromArrayExpr(p, s, !required.has(p));
  return `            ${id}: ${val},`;
}).join('\n')}
        );
    }

    /** Serialize to a plain array suitable for json_encode. */
    public function toArray(): array
    {
        return array_filter([
${Object.entries(props).map(([p]) => {
  const id = $camel(p);
  return `            '${p}' => $this->${id},`;
}).join('\n')}
        ], fn($v) => $v !== null);
    }
}
`;
  }

  private fromArrayExpr(propName: string, schema: SchemaObject, nullable: boolean): string {
    const key = `$data['${propName}'] ?? null`;
    if (schema['x-schema-name'] ?? schema.$ref) {
      const cls = this.toPascalCase(schema['x-schema-name'] ?? schema.$ref!.split('/').pop()!);
      return nullable
        ? `isset($data['${propName}']) ? ${cls}::fromArray($data['${propName}']) : null`
        : `${cls}::fromArray($data['${propName}'])`;
    }
    if (schema.type === 'array' && schema.items) {
      const innerRef = schema.items['x-schema-name'] ?? schema.items.$ref?.split('/').pop();
      if (innerRef) {
        const cls = this.toPascalCase(innerRef);
        return `array_map(fn($i) => ${cls}::fromArray($i), $data['${propName}'] ?? [])`;
      }
    }
    return key;
  }

  // ── ApiException.php ──────────────────────────────────────────────────────

  private renderApiException(): string {
    return `<?php
// @generated Code generated by Steel Core — do not edit manually.
declare(strict_types=1);

namespace ${this.ns};

class ApiException extends \\RuntimeException
{
    public function __construct(
        public readonly int    $statusCode,
        public readonly string $body,
        public readonly string $url,
    ) {
        parent::__construct(
            sprintf('HTTP %d %s: %s', $statusCode, $url, substr($body, 0, 200))
        );
    }

    public function isRetryable(): bool
    {
        return $this->statusCode === 429
            || ($this->statusCode >= 500 && $this->statusCode < 600);
    }
}

class RateLimitException extends ApiException {}

class AuthException extends ApiException {}
`;
  }

  // ── RetryConfig.php ───────────────────────────────────────────────────────

  private renderRetryConfig(): string {
    return `<?php
// @generated Code generated by Steel Core — do not edit manually.
declare(strict_types=1);

namespace ${this.ns};

readonly class RetryConfig
{
    public function __construct(
        /** Number of retry attempts after the first failure. */
        public int   $maxRetries = 3,
        /** Initial backoff in seconds. */
        public float $baseDelay  = 1.0,
        /** Maximum backoff in seconds. */
        public float $maxDelay   = 60.0,
        /** Add ±25% jitter to backoff. */
        public bool  $jitter     = true,
    ) {}

    public static function default(): self { return new self(); }
    public static function none(): self    { return new self(maxRetries: 0); }
}
`;
  }

  // ── HttpTransport.php ─────────────────────────────────────────────────────

  private renderHttpTransport(): string {
    return `<?php
// @generated Code generated by Steel Core — do not edit manually.
declare(strict_types=1);

namespace ${this.ns};

/**
 * Internal HTTP transport using ext-curl.
 * Compatible with PSR-7 environments when wrapped.
 */
class HttpTransport
{
    private const RETRYABLE_STATUS = [429, 500, 502, 503, 504];

    /** @param array<string,string> $headers */
    public function __construct(
        private readonly string      $baseUrl,
        private readonly array       $headers,
        private readonly RetryConfig $retry,
        private readonly int         $timeoutSeconds = 30,
    ) {}

    /**
     * Execute an HTTP request with automatic retry.
     *
     * @param  array<string,mixed>|null $params  Query parameters
     * @param  mixed                    $body    JSON-serializable body
     * @return mixed  Decoded JSON response, or null for 204
     * @throws ApiException
     */
    public function request(
        string $method,
        string $path,
        ?array $params = null,
        mixed  $body   = null,
    ): mixed {
        $url       = $this->buildUrl($path, $params);
        $lastError = null;

        for ($attempt = 0; $attempt <= $this->retry->maxRetries; $attempt++) {
            if ($attempt > 0) {
                usleep((int) ($this->backoff($attempt - 1) * 1_000_000));
            }

            [$status, $responseHeaders, $responseBody] = $this->execute($method, $url, $body);

            if (in_array($status, self::RETRYABLE_STATUS, true)
                && $attempt < $this->retry->maxRetries
            ) {
                // Honour Retry-After header
                $retryAfter = $responseHeaders['retry-after'] ?? null;
                if ($retryAfter !== null) {
                    usleep((int) ((float) $retryAfter * 1_000_000));
                    continue;
                }
                $lastError = new ApiException($status, $responseBody, $url);
                continue;
            }

            if ($status < 200 || $status >= 300) {
                throw match (true) {
                    $status === 429        => new RateLimitException($status, $responseBody, $url),
                    in_array($status, [401, 403]) => new AuthException($status, $responseBody, $url),
                    default                => new ApiException($status, $responseBody, $url),
                };
            }

            if ($status === 204 || $responseBody === '') {
                return null;
            }

            return json_decode($responseBody, associative: true, flags: JSON_THROW_ON_ERROR);
        }

        throw $lastError ?? new \\RuntimeException('Request failed after retries');
    }

    /** @return array{int, array<string,string>, string} [status, headers, body] */
    private function execute(string $method, string $url, mixed $body): array
    {
        $ch = curl_init();
        curl_setopt_array($ch, [
            CURLOPT_URL            => $url,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT        => $this->timeoutSeconds,
            CURLOPT_CUSTOMREQUEST  => strtoupper($method),
            CURLOPT_HEADER         => false,
        ]);

        $responseHeaders = [];
        curl_setopt($ch, CURLOPT_HEADERFUNCTION, function ($ch, $line) use (&$responseHeaders) {
            $trimmed = trim($line);
            if (str_contains($trimmed, ':')) {
                [$k, $v] = explode(':', $trimmed, 2);
                $responseHeaders[strtolower(trim($k))] = trim($v);
            }
            return strlen($line);
        });

        $curlHeaders = array_map(
            fn($k, $v) => "$k: $v",
            array_keys($this->headers),
            array_values($this->headers),
        );

        if ($body !== null) {
            $json = json_encode($body, JSON_THROW_ON_ERROR);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $json);
            $curlHeaders[] = 'Content-Type: application/json';
        }

        curl_setopt($ch, CURLOPT_HTTPHEADER, $curlHeaders);

        $responseBody = curl_exec($ch);
        $status       = curl_getinfo($ch, CURLINFO_HTTP_CODE);

        if ($responseBody === false) {
            $error = curl_error($ch);
            curl_close($ch);
            throw new \\RuntimeException('cURL error: ' . $error);
        }

        curl_close($ch);

        return [$status, $responseHeaders, (string) $responseBody];
    }

    private function backoff(int $attempt): float
    {
        $delay = min(
            $this->retry->baseDelay * (2 ** $attempt),
            $this->retry->maxDelay,
        );
        if ($this->retry->jitter) {
            $delay *= (0.75 + (random_int(0, 100) / 200));
        }
        return $delay;
    }

    /** @param array<string,mixed>|null $params */
    private function buildUrl(string $path, ?array $params): string
    {
        $url = rtrim($this->baseUrl, '/') . $path;
        if (!empty($params)) {
            $filtered = array_filter($params, fn($v) => $v !== null);
            if ($filtered) {
                $url .= '?' . http_build_query($filtered);
            }
        }
        return $url;
    }
}
`;
  }

  // ── CursorPage.php ────────────────────────────────────────────────────────

  private renderCursorPage(): string {
    return `<?php
// @generated Code generated by Steel Core — do not edit manually.
declare(strict_types=1);

namespace ${this.ns};

/**
 * A cursor-paginated result set. Implements \\IteratorAggregate for transparent
 * auto-pagination with foreach.
 *
 * @template T
 * @implements \\IteratorAggregate<int, T>
 */
class CursorPage implements \\IteratorAggregate, \\Countable
{
    /** @param T[]                             $items
     *  @param \\Closure(string): CursorPage<T> $fetch */
    public function __construct(
        public readonly array    $items,
        public readonly ?string  $nextCursor,
        public readonly bool     $hasNext,
        private readonly \\Closure $fetch,
    ) {}

    /**
     * Iterate all items across all pages lazily.
     *
     * @return \\Generator<int, T>
     */
    public function getIterator(): \\Generator
    {
        $page = $this;
        do {
            yield from $page->items;
            if (!$page->hasNext) break;
            $page = ($page->fetch)($page->nextCursor);
        } while (true);
    }

    /** Collect all items from all pages into an array. */
    public function toArray(): array
    {
        return iterator_to_array($this->getIterator(), preserve_keys: false);
    }

    public function count(): int { return count($this->items); }
}
`;
  }

  // ── OffsetPage.php ────────────────────────────────────────────────────────

  private renderOffsetPage(): string {
    return `<?php
// @generated Code generated by Steel Core — do not edit manually.
declare(strict_types=1);

namespace ${this.ns};

/**
 * An offset/limit-paginated result set. Implements \\IteratorAggregate.
 *
 * @template T
 * @implements \\IteratorAggregate<int, T>
 */
class OffsetPage implements \\IteratorAggregate, \\Countable
{
    public readonly bool $hasNext;

    /** @param T[]                                           $items
     *  @param \\Closure(int, int): OffsetPage<T>            $fetch */
    public function __construct(
        public readonly array    $items,
        public readonly ?int     $total,
        public readonly int      $offset,
        public readonly int      $limit,
        private readonly \\Closure $fetch,
    ) {
        $this->hasNext = $total === null || ($offset + count($items)) < $total;
    }

    /**
     * Iterate all items across all pages lazily.
     *
     * @return \\Generator<int, T>
     */
    public function getIterator(): \\Generator
    {
        $page = $this;
        do {
            yield from $page->items;
            if (!$page->hasNext) break;
            $page = ($page->fetch)($page->offset + $page->limit, $page->limit);
        } while (true);
    }

    /** Collect all items from all pages into an array. */
    public function toArray(): array
    {
        return iterator_to_array($this->getIterator(), preserve_keys: false);
    }

    public function count(): int { return count($this->items); }
}
`;
  }

  // ── Client ────────────────────────────────────────────────────────────────

  private renderClient(
    spec: OpenAPISpec,
    operations: ReturnType<OpenAPIParser['getOperations']>,
  ): string {
    const methods = operations.map((op) => this.renderMethod(op)).join('\n\n');
    return `<?php
// @generated Code generated by Steel Core — do not edit manually.
declare(strict_types=1);

namespace ${this.ns};

/**
 * ${spec.info.title} v${spec.info.version} API client.
 */
class ${this.className}
{
    private HttpTransport $http;

    public function __construct(
        string       $baseUrl,
        ?string      $apiKey  = null,
        RetryConfig  $retry   = new RetryConfig(),
        int          $timeout = 30,
    ) {
        $headers = ['Accept' => 'application/json'];
        if ($apiKey !== null) {
            $headers['Authorization'] = "Bearer {$apiKey}";
        }
        $this->http = new HttpTransport($baseUrl, $headers, $retry, $timeout);
    }

${methods}
}
`;
  }

  private renderMethod(op: { path: string; method: string; operation: Operation }): string {
    const name = op.operation.operationId
      ? $camel(op.operation.operationId)
      : `${op.method.toLowerCase()}${this.toPascalCase(op.path.replace(/[{}]/g, '').replace(/\//g, '_'))}`;

    const pathParams = (op.operation.parameters ?? [])
      .filter((p) => p.in === 'path')
      .map((p) => `string $${$camel(p.name)}`);

    const queryParams = (op.operation.parameters ?? [])
      .filter((p) => p.in === 'query');

    const bodySchema = op.operation.requestBody
      ? this.parser.getRequestBodySchema(op.operation) : null;
    const bodyPhpType = bodySchema?.['x-schema-name']
      ? `?${this.toPascalCase(bodySchema['x-schema-name'])}`
      : bodySchema ? 'mixed' : null;
    const bodyParam = bodyPhpType ? [`${bodyPhpType} $body = null`] : [];

    const returnSchema = this.parser.getResponseSchema(op.operation);
    const rawReturn    = returnSchema?.['x-schema-name']
      ? this.toPascalCase(returnSchema['x-schema-name'])
      : null;

    const isPaginated = this.isPaginatedResponse(returnSchema);
    const itemType    = isPaginated ? this.getPaginationItemType(returnSchema!) : null;
    const hasCursor   = isPaginated && returnSchema?.properties?.['next_cursor'] != null;
    const pageClass   = hasCursor ? 'CursorPage' : 'OffsetPage';
    const returnHint  = isPaginated ? `${pageClass}` : rawReturn ?? 'mixed';

    const queryParamsList = queryParams.map((p) => {
      const t = this.schemaToPhpType(p.schema, true);
      return `${t} $${$camel(p.name)} = null`;
    });

    const allParams = [...pathParams, ...queryParamsList, ...bodyParam].join(', ');
    const urlPath   = op.path.replace(/{(\w+)}/g, (_, k) => `{$${$camel(k)}}`);
    const doc       = op.operation.summary ? `    /** ${op.operation.summary} */\n` : '';

    const queryArr = queryParams
      .map((p) => `'${p.name}' => $${$camel(p.name)}`)
      .join(', ');
    const paramsExpr = queryArr ? `[${queryArr}]` : 'null';
    const bodyArg = bodyPhpType ? ', $body' : '';

    if (isPaginated) {
      return hasCursor
        ? this.renderCursorMethod(name, doc, allParams, urlPath, paramsExpr, itemType!, pageClass)
        : this.renderOffsetMethod(name, doc, allParams, urlPath, paramsExpr, itemType!, pageClass);
    }

    if (!rawReturn) {
      return `${doc}    public function ${name}(${allParams}): mixed
    {
        return $this->http->request('${op.method.toUpperCase()}', "${urlPath}", ${paramsExpr}${bodyArg});
    }`;
    }

    return `${doc}    public function ${name}(${allParams}): ?${returnHint}
    {
        $data = $this->http->request('${op.method.toUpperCase()}', "${urlPath}", ${paramsExpr}${bodyArg});
        return $data !== null ? ${rawReturn}::fromArray($data) : null;
    }`;
  }

  private renderCursorMethod(
    name: string, doc: string, params: string, urlPath: string,
    paramsExpr: string, itemType: string, pageClass: string,
  ): string {
    const sig = params ? `${params}, int $limit = 50, ?string $cursor = null` : 'int $limit = 50, ?string $cursor = null';
    return `${doc}    public function ${name}(${sig}): ${pageClass}
    {
        $fetch = function (?string $cur) use ($limit, ${paramsExpr !== 'null' ? paramsExpr.replace(/'/g, '"').match(/\$\w+/g)?.map((v) => $camel(v.slice(1))).map((v) => `$${v}`).join(', ') ?? '' : ''}): CursorPage {
            $params = array_merge(${paramsExpr} ?? [], ['limit' => $limit]);
            if ($cur !== null) $params['cursor'] = $cur;
            $raw   = $this->http->request('GET', "${urlPath}", $params);
            $items = array_map(fn($i) => ${itemType}::fromArray($i), $raw['items'] ?? []);
            return new CursorPage($items, $raw['next_cursor'] ?? null, isset($raw['next_cursor']), $fetch);
        };
        return $fetch($cursor);
    }`;
  }

  private renderOffsetMethod(
    name: string, doc: string, params: string, urlPath: string,
    paramsExpr: string, itemType: string, pageClass: string,
  ): string {
    const sig = params ? `${params}, int $limit = 50, int $offset = 0` : 'int $limit = 50, int $offset = 0';
    return `${doc}    public function ${name}(${sig}): ${pageClass}
    {
        $fetch = function (int $off, int $lim): OffsetPage {
            $params = array_merge(${paramsExpr} ?? [], ['limit' => $lim, 'offset' => $off]);
            $raw    = $this->http->request('GET', "${urlPath}", $params);
            $items  = array_map(fn($i) => ${itemType}::fromArray($i), $raw['items'] ?? []);
            return new OffsetPage($items, $raw['total'] ?? null, $off, $lim, $fetch);
        };
        return $fetch($offset, $limit);
    }`;
  }

  // ── composer.json ─────────────────────────────────────────────────────────

  private renderComposer(spec: OpenAPISpec): string {
    const pkg = `example/${this.ns.toLowerCase()}`;
    return JSON.stringify({
      name: pkg,
      description: spec.info.description ?? `${spec.info.title} API client`,
      version: spec.info.version,
      type: 'library',
      license: 'MIT',
      require: { php: '>=8.2', 'ext-curl': '*' },
      autoload: { 'psr-4': { [`${this.ns}\\`]: 'src/' } },
      'require-dev': { 'phpunit/phpunit': '^11.0' },
    }, null, 4) + '\n';
  }

  // ── Pagination detection ───────────────────────────────────────────────────

  private isPaginatedResponse(schema: SchemaObject | null): boolean {
    if (!schema?.properties) return false;
    return 'items' in schema.properties && schema.properties['items'].type === 'array';
  }

  private getPaginationItemType(schema: SchemaObject): string {
    const items = schema.properties!['items'];
    return items.items?.['x-schema-name']
      ? this.toPascalCase(items.items['x-schema-name'])
      : 'array';
  }

  // ── Type helpers ──────────────────────────────────────────────────────────

  private schemaToPhpType(schema: SchemaObject, nullable = false): string {
    const base = this.basePhpType(schema);
    return nullable && !base.startsWith('?') ? `?${base}` : base;
  }

  private basePhpType(schema: SchemaObject): string {
    if (schema.$ref || schema['x-schema-name']) {
      return this.toPascalCase(schema['x-schema-name'] ?? schema.$ref!.split('/').pop()!);
    }
    if (schema.oneOf ?? schema.anyOf) return 'mixed';
    if (schema.nullable) return `?${this.basePhpType({ ...schema, nullable: false })}`;

    switch (schema.type) {
      case 'string':  return 'string';
      case 'integer': return 'int';
      case 'number':  return 'float';
      case 'boolean': return 'bool';
      case 'array':   return 'array';
      case 'object':  return 'array';
      default:        return 'mixed';
    }
  }

  // ── String helpers ────────────────────────────────────────────────────────

  private toPascalCase(str: string): string {
    return str
      .replace(/[-_./](\w)/g, (_, c: string) => c.toUpperCase())
      .replace(/^[a-z]/, (c) => c.toUpperCase())
      .replace(/[^a-zA-Z0-9]/g, '');
  }
}

// module-level camelCase helper (avoids `this` in template expressions)
function $camel(str: string): string {
  return str
    .replace(/[-_./](\w)/g, (_, c: string) => c.toUpperCase())
    .replace(/^[A-Z]/, (c) => c.toLowerCase())
    .replace(/[^a-zA-Z0-9]/g, '');
}
