import * as fs from 'fs';
import * as path from 'path';
import { OpenAPISpec, OpenAPIParser } from '@steel-core/core';

export default class TypeScriptGenerator {
  async generate(spec: OpenAPISpec, outputDir: string): Promise<void> {
    fs.mkdirSync(outputDir, { recursive: true });

    const parser = new OpenAPIParser();
    const operations = parser.getOperations(spec);
    const className = this.toClassName(spec.info.title);

    fs.writeFileSync(path.join(outputDir, 'client.ts'), this.renderClient(className, spec, operations));
    fs.writeFileSync(path.join(outputDir, 'index.ts'), `export { ${className} } from './client';\n`);
    fs.writeFileSync(path.join(outputDir, 'package.json'), JSON.stringify({
      name: this.toPackageName(spec.info.title),
      version: spec.info.version,
      main: 'client.js',
      types: 'client.d.ts',
    }, null, 2) + '\n');

    console.log(`  Created: client.ts, index.ts, package.json`);
  }

  private renderClient(
    className: string,
    spec: OpenAPISpec,
    operations: ReturnType<OpenAPIParser['getOperations']>
  ): string {
    const methods = operations.map((op) => this.renderMethod(op)).join('\n\n');

    return `/**
 * ${spec.info.title} v${spec.info.version} — auto-generated by Steel Core
 */

export class ${className} {
  private readonly baseUrl: string;
  private readonly headers: Record<string, string>;

  constructor(baseUrl: string, apiKey?: string) {
    this.baseUrl = baseUrl.replace(/\\/$/, '');
    this.headers = { 'Content-Type': 'application/json' };
    if (apiKey) this.headers['Authorization'] = \`Bearer \${apiKey}\`;
  }

  private async request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const res = await fetch(\`\${this.baseUrl}\${path}\`, {
      method,
      headers: this.headers,
      body: body !== undefined ? JSON.stringify(body) : undefined,
    });
    if (!res.ok) throw new Error(\`HTTP \${res.status}: \${await res.text()}\`);
    return res.json() as Promise<T>;
  }

${methods}
}
`;
  }

  private renderMethod(op: { path: string; method: string; operation: import('@steel-core/core').Operation }): string {
    const name = op.operation.operationId
      ? this.toCamelCase(op.operation.operationId)
      : `${op.method}${this.toPascalCase(op.path.replace(/[{}]/g, '').replace(/\//g, '_'))}`;

    const pathParams = (op.operation.parameters ?? [])
      .filter((p) => p.in === 'path')
      .map((p) => `${this.toCamelCase(p.name)}: string`);

    const queryParams = (op.operation.parameters ?? [])
      .filter((p) => p.in === 'query')
      .map((p) => `${this.toCamelCase(p.name)}?: string`);

    const hasBody = !!op.operation.requestBody;
    const bodyParam = hasBody ? ['body?: Record<string, unknown>'] : [];

    const allParams = [...pathParams, ...queryParams, ...bodyParam].join(', ');
    const urlPath = op.path.replace(/{(\w+)}/g, '${$1}');
    const docstring = op.operation.summary ?? '';

    return `  /** ${docstring} */
  async ${name}(${allParams}): Promise<unknown> {
    return this.request('${op.method.toUpperCase()}', \`${urlPath}\`${hasBody ? ', body' : ''});
  }`;
  }

  private toClassName(title: string): string {
    return title.replace(/[^a-zA-Z0-9]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()).replace(/\s/g, '') + 'Client';
  }

  private toPackageName(title: string): string {
    return title.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-');
  }

  private toCamelCase(str: string): string {
    return str.replace(/[_-](\w)/g, (_, c: string) => c.toUpperCase()).replace(/^[A-Z]/, (c) => c.toLowerCase());
  }

  private toPascalCase(str: string): string {
    return str.replace(/[_-](\w)/g, (_, c: string) => c.toUpperCase()).replace(/^[a-z]/, (c) => c.toUpperCase());
  }
}
