import * as fs from 'fs';
import * as path from 'path';
import { OpenAPISpec, OpenAPIParser, SchemaObject, ResolvedModel, Operation } from '@steel-core/core';

export default class GoGenerator {
  private parser!: OpenAPIParser;
  private moduleName!: string;

  async generate(spec: OpenAPISpec, outputDir: string): Promise<void> {
    fs.mkdirSync(outputDir, { recursive: true });
    this.parser = new OpenAPIParser();
    this.parser.parse(spec);
    this.moduleName = this.toPackageName(spec.info.title);

    const models = this.parser.getModels();
    const operations = this.parser.getOperations(spec);

    fs.writeFileSync(path.join(outputDir, 'models.go'), this.renderModels(models));
    fs.writeFileSync(path.join(outputDir, 'http.go'), this.renderHttpLayer());
    fs.writeFileSync(path.join(outputDir, 'pagination.go'), this.renderPagination());
    fs.writeFileSync(path.join(outputDir, 'client.go'), this.renderClient(spec, operations));
    fs.writeFileSync(path.join(outputDir, 'go.mod'), this.renderGoMod(spec));

    console.log(`  Created: models.go, http.go, pagination.go, client.go, go.mod`);
  }

  // ── go.mod ────────────────────────────────────────────────────────────────

  private renderGoMod(spec: OpenAPISpec): string {
    return `module github.com/example/${this.moduleName}

go 1.21
`;
  }

  // ── models.go ─────────────────────────────────────────────────────────────

  private renderModels(models: ResolvedModel[]): string {
    const structs = models.map((m) => this.renderModel(m.name, m.schema)).join('\n\n');
    return `// Code generated by Steel Core — do not edit manually.
package ${this.moduleName}
${structs}
`;
  }

  private renderModel(name: string, schema: SchemaObject): string {
    // Enum → typed string constants
    if (schema.enum) {
      const typeName = this.toPascalCase(name);
      const members = schema.enum
        .map((v) => `\t${typeName}${this.toPascalCase(String(v))} ${typeName} = ${JSON.stringify(v)}`)
        .join('\n');
      return `type ${typeName} string\n\nconst (\n${members}\n)`;
    }

    // oneOf/anyOf → interface{} alias with a comment
    if (schema.oneOf ?? schema.anyOf) {
      const variants = (schema.oneOf ?? schema.anyOf)!
        .map((s) => this.schemaToGoType(s))
        .join(' | ');
      return `// ${this.toPascalCase(name)} is one of: ${variants}\ntype ${this.toPascalCase(name)} interface{}`;
    }

    // Object → struct
    const props = schema.properties ?? {};
    const required = new Set(schema.required ?? []);
    const doc = schema.description ? `// ${this.toPascalCase(name)} ${schema.description}\n` : '';

    const fields = Object.entries(props).map(([propName, propSchema]) => {
      const goType = this.schemaToGoType(propSchema, !required.has(propName));
      const fieldName = this.toPascalCase(propName);
      const jsonTag = `\`json:"${propName}${required.has(propName) ? '' : ',omitempty'}"\``;
      const fieldDoc = propSchema.description ? `\t// ${propSchema.description}\n` : '';
      return `${fieldDoc}\t${fieldName} ${goType} ${jsonTag}`;
    });

    const body = fields.length ? fields.join('\n') : '\t// no fields';
    return `${doc}type ${this.toPascalCase(name)} struct {\n${body}\n}`;
  }

  private schemaToGoType(schema: SchemaObject, optional = false): string {
    const base = this.baseGoType(schema);
    // In Go, pointer = optional/nullable
    return optional && !base.startsWith('*') && !base.startsWith('[]') && !base.startsWith('map')
      ? `*${base}`
      : base;
  }

  private baseGoType(schema: SchemaObject): string {
    if (schema.$ref) return this.toPascalCase(schema.$ref.split('/').pop()!);
    if (schema['x-schema-name']) return this.toPascalCase(schema['x-schema-name']);
    if (schema.oneOf ?? schema.anyOf) return 'interface{}';
    if (schema.nullable) return `*${this.baseGoType({ ...schema, nullable: false })}`;

    switch (schema.type) {
      case 'string':
        if (schema.enum) return this.toPascalCase(schema['x-schema-name'] ?? 'string');
        if (schema.format === 'date-time') return 'time.Time';
        if (schema.format === 'uuid') return 'string';
        return 'string';
      case 'integer':
        return schema.format === 'int32' ? 'int32' : 'int64';
      case 'number':
        return schema.format === 'float' ? 'float32' : 'float64';
      case 'boolean': return 'bool';
      case 'array':   return `[]${schema.items ? this.baseGoType(schema.items) : 'interface{}'}`;
      case 'object':
        if (schema.additionalProperties && typeof schema.additionalProperties === 'object') {
          return `map[string]${this.baseGoType(schema.additionalProperties as SchemaObject)}`;
        }
        return 'map[string]interface{}';
      default:        return 'interface{}';
    }
  }

  // ── http.go ───────────────────────────────────────────────────────────────

  private renderHttpLayer(): string {
    const pkg = this.moduleName;
    return `// Code generated by Steel Core — do not edit manually.
package ${pkg}

import (
\t"bytes"
\t"context"
\t"encoding/json"
\t"fmt"
\t"io"
\t"math"
\t"math/rand"
\t"net/http"
\t"net/url"
\t"strconv"
\t"strings"
\t"time"
)

// RetryConfig configures automatic retry behaviour.
type RetryConfig struct {
\t// MaxRetries is the number of retries after the first attempt. Default: 3.
\tMaxRetries int
\t// BaseDelay is the initial backoff duration. Default: 1s.
\tBaseDelay time.Duration
\t// MaxDelay caps the backoff duration. Default: 60s.
\tMaxDelay time.Duration
\t// Jitter adds ±25% randomness to backoff. Default: true.
\tJitter bool
}

func defaultRetry() RetryConfig {
\treturn RetryConfig{MaxRetries: 3, BaseDelay: time.Second, MaxDelay: 60 * time.Second, Jitter: true}
}

var retryableStatus = map[int]bool{429: true, 500: true, 502: true, 503: true, 504: true}

func backoff(attempt int, cfg RetryConfig) time.Duration {
\td := time.Duration(float64(cfg.BaseDelay) * math.Pow(2, float64(attempt)))
\tif d > cfg.MaxDelay {
\t\td = cfg.MaxDelay
\t}
\tif cfg.Jitter {
\t\t// ±25% jitter
\t\td = time.Duration(float64(d) * (0.75 + rand.Float64()*0.5))
\t}
\treturn d
}

// APIError is returned for non-2xx responses.
type APIError struct {
\tStatusCode int
\tURL        string
\tBody       string
}

func (e *APIError) Error() string {
\treturn fmt.Sprintf("HTTP %d %s: %s", e.StatusCode, e.URL, e.Body)
}

type httpClient struct {
\tbaseURL string
\theaders map[string]string
\tretry   RetryConfig
\tclient  *http.Client
}

func newHTTPClient(baseURL string, headers map[string]string, retry RetryConfig) *httpClient {
\treturn &httpClient{
\t\tbaseURL: strings.TrimRight(baseURL, "/"),
\t\theaders: headers,
\t\tretry:   retry,
\t\tclient:  &http.Client{Timeout: 30 * time.Second},
\t}
}

func (c *httpClient) do(ctx context.Context, method, path string, params url.Values, body interface{}) ([]byte, int, error) {
\tvar bodyReader io.Reader
\tif body != nil {
\t\tb, err := json.Marshal(body)
\t\tif err != nil {
\t\t\treturn nil, 0, fmt.Errorf("marshal body: %w", err)
\t\t}
\t\tbodyReader = bytes.NewReader(b)
\t}

\tfullURL := c.baseURL + path
\tif len(params) > 0 {
\t\tfullURL += "?" + params.Encode()
\t}

\tvar lastErr error
\tfor attempt := 0; attempt <= c.retry.MaxRetries; attempt++ {
\t\tif attempt > 0 {
\t\t\twait := backoff(attempt-1, c.retry)
\t\t\tselect {
\t\t\tcase <-time.After(wait):
\t\t\tcase <-ctx.Done():
\t\t\t\treturn nil, 0, ctx.Err()
\t\t\t}
\t\t}

\t\treq, err := http.NewRequestWithContext(ctx, method, fullURL, bodyReader)
\t\tif err != nil {
\t\t\treturn nil, 0, err
\t\t}
\t\tfor k, v := range c.headers {
\t\t\treq.Header.Set(k, v)
\t\t}
\t\tif body != nil {
\t\t\treq.Header.Set("Content-Type", "application/json")
\t\t}
\t\t// Reset body reader on retry
\t\tif bodyReader != nil {
\t\t\tif rs, ok := bodyReader.(*bytes.Reader); ok {
\t\t\t\trs.Seek(0, io.SeekStart)
\t\t\t}
\t\t}

\t\tresp, err := c.client.Do(req)
\t\tif err != nil {
\t\t\tlastErr = err
\t\t\tcontinue // retry on network error
\t\t}
\t\tdefer resp.Body.Close()
\t\trespBody, _ := io.ReadAll(resp.Body)

\t\tif retryableStatus[resp.StatusCode] && attempt < c.retry.MaxRetries {
\t\t\t// Honour Retry-After header
\t\t\tif ra := resp.Header.Get("Retry-After"); ra != "" {
\t\t\t\tif secs, err := strconv.ParseFloat(ra, 64); err == nil {
\t\t\t\t\ttime.Sleep(time.Duration(secs * float64(time.Second)))
\t\t\t\t\tcontinue
\t\t\t\t}
\t\t\t}
\t\t\tlastErr = &APIError{resp.StatusCode, fullURL, string(respBody)}
\t\t\tcontinue
\t\t}

\t\tif resp.StatusCode < 200 || resp.StatusCode >= 300 {
\t\t\treturn nil, resp.StatusCode, &APIError{resp.StatusCode, fullURL, string(respBody)}
\t\t}
\t\treturn respBody, resp.StatusCode, nil
\t}
\tif lastErr != nil {
\t\treturn nil, 0, lastErr
\t}
\treturn nil, 0, fmt.Errorf("request failed after %d retries", c.retry.MaxRetries)
}
`;
  }

  // ── pagination.go ─────────────────────────────────────────────────────────

  private renderPagination(): string {
    const pkg = this.moduleName;
    return `// Code generated by Steel Core — do not edit manually.
package ${pkg}

import "context"

// CursorPage is a cursor-paginated result set.
// Use Iter() to iterate all items across pages automatically.
type CursorPage[T any] struct {
\tItems      []T
\tNextCursor *string
\tHasNext    bool
\tfetch      func(ctx context.Context, cursor string) (*CursorPage[T], error)
}

// Iter calls fn for every item, fetching subsequent pages as needed.
func (p *CursorPage[T]) Iter(ctx context.Context, fn func(T) error) error {
\tcurrent := p
\tfor current != nil {
\t\tfor _, item := range current.Items {
\t\t\tif err := fn(item); err != nil {
\t\t\t\treturn err
\t\t\t}
\t\t}
\t\tif current.NextCursor == nil {
\t\t\tbreak
\t\t}
\t\tnext, err := current.fetch(ctx, *current.NextCursor)
\t\tif err != nil {
\t\t\treturn err
\t\t}
\t\tcurrent = next
\t}
\treturn nil
}

// Collect returns all items across all pages as a slice.
func (p *CursorPage[T]) Collect(ctx context.Context) ([]T, error) {
\tvar out []T
\treturn out, p.Iter(ctx, func(item T) error {
\t\tout = append(out, item)
\t\treturn nil
\t})
}

// OffsetPage is an offset/limit-paginated result set.
type OffsetPage[T any] struct {
\tItems   []T
\tTotal   *int64
\tOffset  int64
\tLimit   int64
\tHasNext bool
\tfetch   func(ctx context.Context, offset, limit int64) (*OffsetPage[T], error)
}

// Iter calls fn for every item, fetching subsequent pages as needed.
func (p *OffsetPage[T]) Iter(ctx context.Context, fn func(T) error) error {
\tcurrent := p
\tfor current != nil {
\t\tfor _, item := range current.Items {
\t\t\tif err := fn(item); err != nil {
\t\t\t\treturn err
\t\t\t}
\t\t}
\t\tif !current.HasNext {
\t\t\tbreak
\t\t}
\t\tnext, err := current.fetch(ctx, current.Offset+current.Limit, current.Limit)
\t\tif err != nil {
\t\t\treturn err
\t\t}
\t\tcurrent = next
\t}
\treturn nil
}

// Collect returns all items across all pages as a slice.
func (p *OffsetPage[T]) Collect(ctx context.Context) ([]T, error) {
\tvar out []T
\treturn out, p.Iter(ctx, func(item T) error {
\t\tout = append(out, item)
\t\treturn nil
\t})
}
`;
  }

  // ── client.go ─────────────────────────────────────────────────────────────

  private renderClient(
    spec: OpenAPISpec,
    operations: ReturnType<OpenAPIParser['getOperations']>,
  ): string {
    const pkg = this.moduleName;
    const className = this.toPascalCase(spec.info.title) + 'Client';

    // Collect imports needed across all methods
    const needsTime = this.hasDateTimeField(spec);
    const imports = [
      '"context"',
      '"encoding/json"',
      '"net/url"',
      '"strconv"',
      needsTime ? '"time"' : '',
      '"fmt"',
    ].filter(Boolean).join('\n\t');

    const methods = operations.map((op) => this.renderMethod(op, className)).join('\n\n');

    return `// Code generated by Steel Core — do not edit manually.
// ${spec.info.title} v${spec.info.version}
package ${pkg}

import (
\t${imports}
)

// ${className} is the API client.
type ${className} struct {
\thttp *httpClient
}

// ClientOption configures the client.
type ClientOption func(*${className})

// WithRetry sets a custom retry configuration.
func WithRetry(cfg RetryConfig) ClientOption {
\treturn func(c *${className}) { c.http.retry = cfg }
}

// WithTimeout sets the HTTP timeout (default 30s).
func WithTimeout(d int) ClientOption {
\treturn func(c *${className}) { c.http.client.Timeout = time.Duration(d) * time.Millisecond }
}

// New${className} creates a new client.
func New${className}(baseURL string, apiKey string, opts ...ClientOption) *${className} {
\theaders := map[string]string{"Content-Type": "application/json"}
\tif apiKey != "" {
\t\theaders["Authorization"] = "Bearer " + apiKey
\t}
\tc := &${className}{http: newHTTPClient(baseURL, headers, defaultRetry())}
\tfor _, opt := range opts {
\t\topt(c)
\t}
\treturn c
}

${methods}
`;
  }

  private renderMethod(
    op: { path: string; method: string; operation: Operation },
    clientType: string,
  ): string {
    const name = op.operation.operationId
      ? this.toPascalCase(op.operation.operationId)
      : `${this.toPascalCase(op.method)}${this.toPascalCase(op.path.replace(/[{}]/g, '').replace(/\//g, '_'))}`;

    const pathParams = (op.operation.parameters ?? [])
      .filter((p) => p.in === 'path')
      .map((p) => `${this.toCamelCase(p.name)} ${this.schemaToGoType(p.schema)}`);

    const queryParams = (op.operation.parameters ?? [])
      .filter((p) => p.in === 'query');

    const bodySchema = op.operation.requestBody
      ? this.parser.getRequestBodySchema(op.operation) : null;
    const bodyTypeName = bodySchema?.['x-schema-name']
      ? `*${this.toPascalCase(bodySchema['x-schema-name'])}`
      : bodySchema ? 'interface{}' : '';
    const bodyParam = bodyTypeName ? [`body ${bodyTypeName}`] : [];

    const returnSchema = this.parser.getResponseSchema(op.operation);
    const rawReturnType = returnSchema?.['x-schema-name']
      ? this.toPascalCase(returnSchema['x-schema-name'])
      : returnSchema ? this.baseGoType(returnSchema) : '';

    const isPaginated = this.isPaginatedResponse(returnSchema);
    const itemType = isPaginated ? this.getPaginationItemType(returnSchema!) : null;
    const hasCursor = isPaginated && returnSchema?.properties?.['next_cursor'] != null;

    const returnDecl = isPaginated
      ? (hasCursor ? `(*CursorPage[${itemType}], error)` : `(*OffsetPage[${itemType}], error)`)
      : rawReturnType ? `(*${rawReturnType}, error)` : 'error';

    const allGoParams = ['ctx context.Context', ...pathParams, ...bodyParam].join(', ');
    const urlPath = op.path.replace(/{(\w+)}/g, `" + url.PathEscape(fmt.Sprintf("%v", $1)) + "`);
    const urlExpr = `"${urlPath}"`;
    const doc = op.operation.summary ? `// ${name} ${op.operation.summary}` : `// ${name} calls ${op.method.toUpperCase()} ${op.path}`;

    // Build query params block
    let paramsBlock = '';
    if (queryParams.length) {
      const lines = ['\tparams := url.Values{}'];
      for (const p of queryParams) {
        const goName = this.toCamelCase(p.name);
        const goType = this.schemaToGoType(p.schema);
        lines.push(`\tif ${goName} != nil {`);
        if (goType === '*string') {
          lines.push(`\t\tparams.Set(${JSON.stringify(p.name)}, *${goName})`);
        } else if (goType === '*int64' || goType === '*int32') {
          lines.push(`\t\tparams.Set(${JSON.stringify(p.name)}, strconv.FormatInt(int64(*${goName}), 10))`);
        } else {
          lines.push(`\t\tparams.Set(${JSON.stringify(p.name)}, fmt.Sprintf("%v", *${goName}))`);
        }
        lines.push('\t}');
      }
      paramsBlock = lines.join('\n') + '\n';
    }

    // Query param function signature additions
    const queryGoParams = queryParams
      .map((p) => `${this.toCamelCase(p.name)} *${this.baseGoType(p.schema)}`)
      .join(', ');
    const fullSig = [allGoParams, queryGoParams].filter(Boolean).join(', ');

    const paramsArg = queryParams.length ? 'params' : 'nil';
    const bodyArg = bodyTypeName ? 'body' : 'nil';

    if (isPaginated) {
      return hasCursor
        ? this.renderCursorMethod(name, doc, fullSig, clientType, urlExpr, paramsBlock, paramsArg, itemType!, 'CursorPage')
        : this.renderOffsetMethod(name, doc, fullSig, clientType, urlExpr, paramsBlock, paramsArg, itemType!, 'OffsetPage');
    }

    if (!rawReturnType) {
      return `${doc}
func (c *${clientType}) ${name}(${fullSig}) error {
${paramsBlock}\t_, _, err := c.http.do(ctx, "${op.method.toUpperCase()}", ${urlExpr}, ${paramsArg}, ${bodyArg})
\treturn err
}`;
    }

    return `${doc}
func (c *${clientType}) ${name}(${fullSig}) ${returnDecl} {
${paramsBlock}\tbody, _, err := c.http.do(ctx, "${op.method.toUpperCase()}", ${urlExpr}, ${paramsArg}, ${bodyArg})
\tif err != nil {
\t\treturn nil, err
\t}
\tvar result ${rawReturnType}
\tif err := json.Unmarshal(body, &result); err != nil {
\t\treturn nil, err
\t}
\treturn &result, nil
}`;
  }

  private renderCursorMethod(
    name: string, doc: string, sig: string, clientType: string,
    urlExpr: string, paramsBlock: string, paramsArg: string,
    itemType: string, pageClass: string,
  ): string {
    return `${doc}
func (c *${clientType}) ${name}(${sig}) (*${pageClass}[${itemType}], error) {
${paramsBlock}
\ttype pageResp struct {
\t\tItems      []${itemType} \`json:"items"\`
\t\tNextCursor *string      \`json:"next_cursor"\`
\t}

\tvar fetch func(ctx context.Context, cursor string) (*${pageClass}[${itemType}], error)
\tfetch = func(ctx context.Context, cursor string) (*${pageClass}[${itemType}], error) {
\t\tp := url.Values{}
\t\tfor k, v := range ${paramsArg} {
\t\t\tp[k] = v
\t\t}
\t\tif cursor != "" {
\t\t\tp.Set("cursor", cursor)
\t\t}
\t\tbody, _, err := c.http.do(ctx, "GET", ${urlExpr}, p, nil)
\t\tif err != nil {
\t\t\treturn nil, err
\t\t}
\t\tvar resp pageResp
\t\tif err := json.Unmarshal(body, &resp); err != nil {
\t\t\treturn nil, err
\t\t}
\t\treturn &${pageClass}[${itemType}]{
\t\t\tItems: resp.Items, NextCursor: resp.NextCursor,
\t\t\tHasNext: resp.NextCursor != nil, fetch: fetch,
\t\t}, nil
\t}
\treturn fetch(ctx, "")
}`;
  }

  private renderOffsetMethod(
    name: string, doc: string, sig: string, clientType: string,
    urlExpr: string, paramsBlock: string, paramsArg: string,
    itemType: string, pageClass: string,
  ): string {
    return `${doc}
func (c *${clientType}) ${name}(${sig}) (*${pageClass}[${itemType}], error) {
${paramsBlock}
\ttype pageResp struct {
\t\tItems []${itemType} \`json:"items"\`
\t\tTotal *int64       \`json:"total"\`
\t}

\tvar fetch func(ctx context.Context, offset, limit int64) (*${pageClass}[${itemType}], error)
\tfetch = func(ctx context.Context, offset, limit int64) (*${pageClass}[${itemType}], error) {
\t\tp := url.Values{}
\t\tfor k, v := range ${paramsArg} {
\t\t\tp[k] = v
\t\t}
\t\tp.Set("offset", strconv.FormatInt(offset, 10))
\t\tp.Set("limit", strconv.FormatInt(limit, 10))
\t\tbody, _, err := c.http.do(ctx, "GET", ${urlExpr}, p, nil)
\t\tif err != nil {
\t\t\treturn nil, err
\t\t}
\t\tvar resp pageResp
\t\tif err := json.Unmarshal(body, &resp); err != nil {
\t\t\treturn nil, err
\t\t}
\t\thasNext := resp.Total == nil || offset+int64(len(resp.Items)) < *resp.Total
\t\treturn &${pageClass}[${itemType}]{
\t\t\tItems: resp.Items, Total: resp.Total,
\t\t\tOffset: offset, Limit: limit, HasNext: hasNext, fetch: fetch,
\t\t}, nil
\t}
\treturn fetch(ctx, 0, 50)
}`;
  }

  // ── Pagination detection ──────────────────────────────────────────────────

  private isPaginatedResponse(schema: SchemaObject | null): boolean {
    if (!schema?.properties) return false;
    return 'items' in schema.properties && schema.properties['items'].type === 'array';
  }

  private getPaginationItemType(schema: SchemaObject): string {
    const items = schema.properties!['items'];
    return items.items?.['x-schema-name']
      ? this.toPascalCase(items.items['x-schema-name'])
      : this.baseGoType(items.items ?? {});
  }

  private hasDateTimeField(spec: OpenAPISpec): boolean {
    const schemas = spec.components?.schemas ?? {};
    return Object.values(schemas).some((s) =>
      Object.values(s.properties ?? {}).some((p) => p.format === 'date-time')
    );
  }

  // ── String helpers ────────────────────────────────────────────────────────

  private toPascalCase(str: string): string {
    return str
      .replace(/[-_/.](\w)/g, (_, c: string) => c.toUpperCase())
      .replace(/^[a-z]/, (c) => c.toUpperCase())
      .replace(/[^a-zA-Z0-9]/g, '');
  }

  private toCamelCase(str: string): string {
    const pascal = this.toPascalCase(str);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  }

  private toPackageName(title: string): string {
    return title.toLowerCase().replace(/[^a-z0-9]/g, '');
  }
}
